# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'session-zero.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 772)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.startPage = QtWidgets.QWidget()
        self.startPage.setObjectName("startPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.startPage)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.startPage)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout_2.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.buildBtn = QtWidgets.QPushButton(self.startPage)
        self.buildBtn.setObjectName("buildBtn")
        self.gridLayout_2.addWidget(self.buildBtn, 3, 0, 1, 1)
        self.loadBtn = QtWidgets.QPushButton(self.startPage)
        self.loadBtn.setObjectName("loadBtn")
        self.gridLayout_2.addWidget(self.loadBtn, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.startPage)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.startPage)
        self.wave1Page1 = QtWidgets.QWidget()
        self.wave1Page1.setObjectName("wave1Page1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.wave1Page1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.nameEdit = QtWidgets.QLineEdit(self.wave1Page1)
        self.nameEdit.setMaxLength(25)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_3.addWidget(self.nameEdit, 3, 1, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.wave1Page1)
        self.nameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_3.addWidget(self.nameLabel, 3, 0, 1, 1)
        self.raceLabel = QtWidgets.QLabel(self.wave1Page1)
        self.raceLabel.setObjectName("raceLabel")
        self.gridLayout_3.addWidget(self.raceLabel, 4, 0, 1, 1)
        self.raceBox = QtWidgets.QComboBox(self.wave1Page1)
        self.raceBox.setObjectName("raceBox")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.gridLayout_3.addWidget(self.raceBox, 4, 1, 1, 1)
        self.classLabel = QtWidgets.QLabel(self.wave1Page1)
        self.classLabel.setObjectName("classLabel")
        self.gridLayout_3.addWidget(self.classLabel, 5, 0, 1, 1)
        self.classBox = QtWidgets.QComboBox(self.wave1Page1)
        self.classBox.setObjectName("classBox")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.gridLayout_3.addWidget(self.classBox, 5, 1, 1, 1)
        self.statsPlusLabel = QtWidgets.QLabel(self.wave1Page1)
        self.statsPlusLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.statsPlusLabel.setObjectName("statsPlusLabel")
        self.gridLayout_3.addWidget(self.statsPlusLabel, 6, 0, 1, 1)
        self.statsMinusLabel = QtWidgets.QLabel(self.wave1Page1)
        self.statsMinusLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.statsMinusLabel.setObjectName("statsMinusLabel")
        self.gridLayout_3.addWidget(self.statsMinusLabel, 7, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_2 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_2.setObjectName("checkBox_2")
        self.statPlusGroup = QtWidgets.QButtonGroup(MainWindow)
        self.statPlusGroup.setObjectName("statPlusGroup")
        self.statPlusGroup.setExclusive(False)
        self.statPlusGroup.addButton(self.checkBox_2)
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_3.setObjectName("checkBox_3")
        self.statPlusGroup.addButton(self.checkBox_3)
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_4.setObjectName("checkBox_4")
        self.statPlusGroup.addButton(self.checkBox_4)
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_5.setObjectName("checkBox_5")
        self.statPlusGroup.addButton(self.checkBox_5)
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_6.setObjectName("checkBox_6")
        self.statPlusGroup.addButton(self.checkBox_6)
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox.setObjectName("checkBox")
        self.statPlusGroup.addButton(self.checkBox)
        self.verticalLayout.addWidget(self.checkBox)
        self.gridLayout_3.addLayout(self.verticalLayout, 6, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_8 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_8.setObjectName("checkBox_8")
        self.statMinusGroup = QtWidgets.QButtonGroup(MainWindow)
        self.statMinusGroup.setObjectName("statMinusGroup")
        self.statMinusGroup.setExclusive(False)
        self.statMinusGroup.addButton(self.checkBox_8)
        self.verticalLayout_2.addWidget(self.checkBox_8)
        self.checkBox_11 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_11.setObjectName("checkBox_11")
        self.statMinusGroup.addButton(self.checkBox_11)
        self.verticalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_10 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_10.setObjectName("checkBox_10")
        self.statMinusGroup.addButton(self.checkBox_10)
        self.verticalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_12 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_12.setObjectName("checkBox_12")
        self.statMinusGroup.addButton(self.checkBox_12)
        self.verticalLayout_2.addWidget(self.checkBox_12)
        self.checkBox_9 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_9.setObjectName("checkBox_9")
        self.statMinusGroup.addButton(self.checkBox_9)
        self.verticalLayout_2.addWidget(self.checkBox_9)
        self.checkBox_7 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_7.setObjectName("checkBox_7")
        self.statMinusGroup.addButton(self.checkBox_7)
        self.verticalLayout_2.addWidget(self.checkBox_7)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 7, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.wave1Page1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 2, 0, 1, 2)
        self.wave1GenBtn = QtWidgets.QPushButton(self.wave1Page1)
        self.wave1GenBtn.setObjectName("wave1GenBtn")
        self.gridLayout_3.addWidget(self.wave1GenBtn, 8, 1, 1, 1)
        self.wave1Label = QtWidgets.QLabel(self.wave1Page1)
        self.wave1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.wave1Label.setObjectName("wave1Label")
        self.gridLayout_3.addWidget(self.wave1Label, 1, 0, 1, 2)
        self.stackedWidget.addWidget(self.wave1Page1)
        self.wave1Results = QtWidgets.QWidget()
        self.wave1Results.setObjectName("wave1Results")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.wave1Results)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.selectBtn2 = QtWidgets.QRadioButton(self.wave1Results)
        self.selectBtn2.setObjectName("selectBtn2")
        self.statblockGroup = QtWidgets.QButtonGroup(MainWindow)
        self.statblockGroup.setObjectName("statblockGroup")
        self.statblockGroup.addButton(self.selectBtn2)
        self.gridLayout_4.addWidget(self.selectBtn2, 4, 0, 1, 1)
        self.selectBtn3 = QtWidgets.QRadioButton(self.wave1Results)
        self.selectBtn3.setObjectName("selectBtn3")
        self.statblockGroup.addButton(self.selectBtn3)
        self.gridLayout_4.addWidget(self.selectBtn3, 5, 0, 1, 1)
        self.selectBtn1 = QtWidgets.QRadioButton(self.wave1Results)
        self.selectBtn1.setChecked(True)
        self.selectBtn1.setObjectName("selectBtn1")
        self.statblockGroup.addButton(self.selectBtn1)
        self.gridLayout_4.addWidget(self.selectBtn1, 3, 0, 1, 1)
        self.statblock1 = QtWidgets.QTableWidget(self.wave1Results)
        self.statblock1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.statblock1.setRowCount(6)
        self.statblock1.setColumnCount(2)
        self.statblock1.setObjectName("statblock1")
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(5, 0, item)
        self.statblock1.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.statblock1, 3, 1, 1, 1)
        self.statblock2 = QtWidgets.QTableWidget(self.wave1Results)
        self.statblock2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.statblock2.setRowCount(6)
        self.statblock2.setColumnCount(2)
        self.statblock2.setObjectName("statblock2")
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(5, 0, item)
        self.statblock2.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.statblock2, 4, 1, 1, 1)
        self.statblock3 = QtWidgets.QTableWidget(self.wave1Results)
        self.statblock3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.statblock3.setRowCount(6)
        self.statblock3.setColumnCount(2)
        self.statblock3.setObjectName("statblock3")
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(5, 0, item)
        self.statblock3.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.statblock3, 5, 1, 1, 1)
        self.wave1EndBtn = QtWidgets.QPushButton(self.wave1Results)
        self.wave1EndBtn.setObjectName("wave1EndBtn")
        self.gridLayout_4.addWidget(self.wave1EndBtn, 6, 1, 1, 1)
        self.statblockLabel = QtWidgets.QLabel(self.wave1Results)
        self.statblockLabel.setObjectName("statblockLabel")
        self.gridLayout_4.addWidget(self.statblockLabel, 2, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.wave1Results)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 1, 0, 1, 2)
        self.genLabel = QtWidgets.QLabel(self.wave1Results)
        self.genLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.genLabel.setObjectName("genLabel")
        self.gridLayout_4.addWidget(self.genLabel, 0, 0, 1, 2)
        self.statblockLabel.raise_()
        self.genLabel.raise_()
        self.statblock1.raise_()
        self.statblock2.raise_()
        self.statblock3.raise_()
        self.selectBtn1.raise_()
        self.selectBtn2.raise_()
        self.selectBtn3.raise_()
        self.wave1EndBtn.raise_()
        self.line_3.raise_()
        self.stackedWidget.addWidget(self.wave1Results)
        self.wave2Page1 = QtWidgets.QWidget()
        self.wave2Page1.setObjectName("wave2Page1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.wave2Page1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line_4 = QtWidgets.QFrame(self.wave2Page1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_5.addWidget(self.line_4, 1, 0, 1, 3)
        self.line_5 = QtWidgets.QFrame(self.wave2Page1)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_5.addWidget(self.line_5, 17, 0, 1, 3)
        self.radioButton_27 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_27.setObjectName("radioButton_27")
        self.friendGroup = QtWidgets.QButtonGroup(MainWindow)
        self.friendGroup.setObjectName("friendGroup")
        self.friendGroup.addButton(self.radioButton_27)
        self.gridLayout_5.addWidget(self.radioButton_27, 23, 0, 1, 1)
        self.radioButton_25 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_25.setObjectName("radioButton_25")
        self.friendGroup.addButton(self.radioButton_25)
        self.gridLayout_5.addWidget(self.radioButton_25, 23, 1, 1, 1)
        self.radioButton_15 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_15.setObjectName("radioButton_15")
        self.senseGroup = QtWidgets.QButtonGroup(MainWindow)
        self.senseGroup.setObjectName("senseGroup")
        self.senseGroup.addButton(self.radioButton_15)
        self.gridLayout_5.addWidget(self.radioButton_15, 19, 2, 1, 1)
        self.radioButton_16 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_16.setObjectName("radioButton_16")
        self.careGroup = QtWidgets.QButtonGroup(MainWindow)
        self.careGroup.setObjectName("careGroup")
        self.careGroup.addButton(self.radioButton_16)
        self.gridLayout_5.addWidget(self.radioButton_16, 20, 1, 1, 1)
        self.radioButton_19 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_19.setObjectName("radioButton_19")
        self.modestGroup = QtWidgets.QButtonGroup(MainWindow)
        self.modestGroup.setObjectName("modestGroup")
        self.modestGroup.addButton(self.radioButton_19)
        self.gridLayout_5.addWidget(self.radioButton_19, 21, 1, 1, 1)
        self.radioButton_21 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_21.setObjectName("radioButton_21")
        self.modestGroup.addButton(self.radioButton_21)
        self.gridLayout_5.addWidget(self.radioButton_21, 21, 2, 1, 1)
        self.radioButton_17 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_17.setObjectName("radioButton_17")
        self.careGroup.addButton(self.radioButton_17)
        self.gridLayout_5.addWidget(self.radioButton_17, 20, 2, 1, 1)
        self.radioButton_20 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_20.setObjectName("radioButton_20")
        self.modestGroup.addButton(self.radioButton_20)
        self.gridLayout_5.addWidget(self.radioButton_20, 21, 0, 1, 1)
        self.radioButton_24 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_24.setObjectName("radioButton_24")
        self.witGroup = QtWidgets.QButtonGroup(MainWindow)
        self.witGroup.setObjectName("witGroup")
        self.witGroup.addButton(self.radioButton_24)
        self.gridLayout_5.addWidget(self.radioButton_24, 22, 0, 1, 1)
        self.radioButton_18 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_18.setObjectName("radioButton_18")
        self.careGroup.addButton(self.radioButton_18)
        self.gridLayout_5.addWidget(self.radioButton_18, 20, 0, 1, 1)
        self.radioButton_22 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_22.setObjectName("radioButton_22")
        self.witGroup.addButton(self.radioButton_22)
        self.gridLayout_5.addWidget(self.radioButton_22, 22, 1, 1, 1)
        self.radioButton_23 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_23.setObjectName("radioButton_23")
        self.witGroup.addButton(self.radioButton_23)
        self.gridLayout_5.addWidget(self.radioButton_23, 22, 2, 1, 1)
        self.radioButton_35 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_35.setObjectName("radioButton_35")
        self.humbleGroup = QtWidgets.QButtonGroup(MainWindow)
        self.humbleGroup.setObjectName("humbleGroup")
        self.humbleGroup.addButton(self.radioButton_35)
        self.gridLayout_5.addWidget(self.radioButton_35, 26, 2, 1, 1)
        self.radioButton_26 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_26.setObjectName("radioButton_26")
        self.friendGroup.addButton(self.radioButton_26)
        self.gridLayout_5.addWidget(self.radioButton_26, 23, 2, 1, 1)
        self.radioButton_37 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_37.setObjectName("radioButton_37")
        self.braveGroup = QtWidgets.QButtonGroup(MainWindow)
        self.braveGroup.setObjectName("braveGroup")
        self.braveGroup.addButton(self.radioButton_37)
        self.gridLayout_5.addWidget(self.radioButton_37, 27, 1, 1, 1)
        self.radioButton_41 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_41.setObjectName("radioButton_41")
        self.moneyGroup = QtWidgets.QButtonGroup(MainWindow)
        self.moneyGroup.setObjectName("moneyGroup")
        self.moneyGroup.addButton(self.radioButton_41)
        self.gridLayout_5.addWidget(self.radioButton_41, 28, 2, 1, 1)
        self.radioButton_33 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_33.setObjectName("radioButton_33")
        self.patientGroup = QtWidgets.QButtonGroup(MainWindow)
        self.patientGroup.setObjectName("patientGroup")
        self.patientGroup.addButton(self.radioButton_33)
        self.gridLayout_5.addWidget(self.radioButton_33, 25, 0, 1, 1)
        self.radioButton_40 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_40.setObjectName("radioButton_40")
        self.moneyGroup.addButton(self.radioButton_40)
        self.gridLayout_5.addWidget(self.radioButton_40, 28, 1, 1, 1)
        self.radioButton_31 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_31.setObjectName("radioButton_31")
        self.patientGroup.addButton(self.radioButton_31)
        self.gridLayout_5.addWidget(self.radioButton_31, 25, 1, 1, 1)
        self.radioButton_29 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_29.setObjectName("radioButton_29")
        self.honestGroup = QtWidgets.QButtonGroup(MainWindow)
        self.honestGroup.setObjectName("honestGroup")
        self.honestGroup.addButton(self.radioButton_29)
        self.gridLayout_5.addWidget(self.radioButton_29, 24, 2, 1, 1)
        self.radioButton_36 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_36.setObjectName("radioButton_36")
        self.humbleGroup.addButton(self.radioButton_36)
        self.gridLayout_5.addWidget(self.radioButton_36, 26, 0, 1, 1)
        self.radioButton_39 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_39.setObjectName("radioButton_39")
        self.braveGroup.addButton(self.radioButton_39)
        self.gridLayout_5.addWidget(self.radioButton_39, 27, 0, 1, 1)
        self.radioButton_32 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_32.setObjectName("radioButton_32")
        self.patientGroup.addButton(self.radioButton_32)
        self.gridLayout_5.addWidget(self.radioButton_32, 25, 2, 1, 1)
        self.radioButton_28 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_28.setObjectName("radioButton_28")
        self.honestGroup.addButton(self.radioButton_28)
        self.gridLayout_5.addWidget(self.radioButton_28, 24, 1, 1, 1)
        self.wave2GenBtn = QtWidgets.QPushButton(self.wave2Page1)
        self.wave2GenBtn.setObjectName("wave2GenBtn")
        self.gridLayout_5.addWidget(self.wave2GenBtn, 29, 1, 1, 1)
        self.radioButton_30 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_30.setObjectName("radioButton_30")
        self.honestGroup.addButton(self.radioButton_30)
        self.gridLayout_5.addWidget(self.radioButton_30, 24, 0, 1, 1)
        self.radioButton_34 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_34.setObjectName("radioButton_34")
        self.humbleGroup.addButton(self.radioButton_34)
        self.gridLayout_5.addWidget(self.radioButton_34, 26, 1, 1, 1)
        self.radioButton_38 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_38.setObjectName("radioButton_38")
        self.braveGroup.addButton(self.radioButton_38)
        self.gridLayout_5.addWidget(self.radioButton_38, 27, 2, 1, 1)
        self.radioButton_42 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_42.setObjectName("radioButton_42")
        self.moneyGroup.addButton(self.radioButton_42)
        self.gridLayout_5.addWidget(self.radioButton_42, 28, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_5.setObjectName("radioButton_5")
        self.traitPlusGrp = QtWidgets.QButtonGroup(MainWindow)
        self.traitPlusGrp.setObjectName("traitPlusGrp")
        self.traitPlusGrp.addButton(self.radioButton_5)
        self.gridLayout_5.addWidget(self.radioButton_5, 7, 1, 1, 2)
        self.radioButton_44 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_44.setObjectName("radioButton_44")
        self.traitPlusGrp.addButton(self.radioButton_44)
        self.gridLayout_5.addWidget(self.radioButton_44, 8, 1, 1, 2)
        self.grtWkLabel = QtWidgets.QLabel(self.wave2Page1)
        self.grtWkLabel.setObjectName("grtWkLabel")
        self.gridLayout_5.addWidget(self.grtWkLabel, 10, 0, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_6.setChecked(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.traitMinusGroup = QtWidgets.QButtonGroup(MainWindow)
        self.traitMinusGroup.setObjectName("traitMinusGroup")
        self.traitMinusGroup.addButton(self.radioButton_6)
        self.gridLayout_5.addWidget(self.radioButton_6, 10, 1, 1, 2)
        self.radioButton = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.traitPlusGrp.addButton(self.radioButton)
        self.gridLayout_5.addWidget(self.radioButton, 2, 1, 1, 2)
        self.grtStrLabel = QtWidgets.QLabel(self.wave2Page1)
        self.grtStrLabel.setObjectName("grtStrLabel")
        self.gridLayout_5.addWidget(self.grtStrLabel, 2, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_2.setObjectName("radioButton_2")
        self.traitPlusGrp.addButton(self.radioButton_2)
        self.gridLayout_5.addWidget(self.radioButton_2, 3, 1, 1, 2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_3.setObjectName("radioButton_3")
        self.traitPlusGrp.addButton(self.radioButton_3)
        self.gridLayout_5.addWidget(self.radioButton_3, 4, 1, 1, 2)
        self.radioButton_4 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_4.setObjectName("radioButton_4")
        self.traitPlusGrp.addButton(self.radioButton_4)
        self.gridLayout_5.addWidget(self.radioButton_4, 5, 1, 1, 2)
        self.radioButton_11 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_11.setObjectName("radioButton_11")
        self.traitPlusGrp.addButton(self.radioButton_11)
        self.gridLayout_5.addWidget(self.radioButton_11, 6, 1, 1, 2)
        self.radioButton_8 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_8.setObjectName("radioButton_8")
        self.traitMinusGroup.addButton(self.radioButton_8)
        self.gridLayout_5.addWidget(self.radioButton_8, 12, 1, 1, 2)
        self.traitsLabel = QtWidgets.QLabel(self.wave2Page1)
        self.traitsLabel.setObjectName("traitsLabel")
        self.gridLayout_5.addWidget(self.traitsLabel, 18, 0, 1, 3)
        self.radioButton_9 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_9.setObjectName("radioButton_9")
        self.traitMinusGroup.addButton(self.radioButton_9)
        self.gridLayout_5.addWidget(self.radioButton_9, 14, 1, 1, 2)
        self.radioButton_12 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_12.setObjectName("radioButton_12")
        self.traitMinusGroup.addButton(self.radioButton_12)
        self.gridLayout_5.addWidget(self.radioButton_12, 15, 1, 1, 2)
        self.radioButton_43 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_43.setObjectName("radioButton_43")
        self.traitMinusGroup.addButton(self.radioButton_43)
        self.gridLayout_5.addWidget(self.radioButton_43, 16, 1, 1, 2)
        self.radioButton_13 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_13.setObjectName("radioButton_13")
        self.senseGroup.addButton(self.radioButton_13)
        self.gridLayout_5.addWidget(self.radioButton_13, 19, 0, 1, 1)
        self.radioButton_14 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_14.setObjectName("radioButton_14")
        self.senseGroup.addButton(self.radioButton_14)
        self.gridLayout_5.addWidget(self.radioButton_14, 19, 1, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_10.setObjectName("radioButton_10")
        self.traitMinusGroup.addButton(self.radioButton_10)
        self.gridLayout_5.addWidget(self.radioButton_10, 13, 1, 1, 2)
        self.radioButton_7 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_7.setObjectName("radioButton_7")
        self.traitMinusGroup.addButton(self.radioButton_7)
        self.gridLayout_5.addWidget(self.radioButton_7, 11, 1, 1, 2)
        self.line_8 = QtWidgets.QFrame(self.wave2Page1)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_5.addWidget(self.line_8, 9, 0, 1, 3)
        self.wave2Label = QtWidgets.QLabel(self.wave2Page1)
        self.wave2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.wave2Label.setObjectName("wave2Label")
        self.gridLayout_5.addWidget(self.wave2Label, 0, 0, 1, 3)
        self.wave2Label.raise_()
        self.grtStrLabel.raise_()
        self.grtWkLabel.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.radioButton_5.raise_()
        self.radioButton_6.raise_()
        self.radioButton_7.raise_()
        self.radioButton_8.raise_()
        self.radioButton_9.raise_()
        self.radioButton_10.raise_()
        self.radioButton_11.raise_()
        self.radioButton_12.raise_()
        self.traitsLabel.raise_()
        self.radioButton_13.raise_()
        self.radioButton_14.raise_()
        self.radioButton_15.raise_()
        self.radioButton_16.raise_()
        self.radioButton_17.raise_()
        self.radioButton_18.raise_()
        self.radioButton_19.raise_()
        self.radioButton_21.raise_()
        self.radioButton_22.raise_()
        self.radioButton_23.raise_()
        self.radioButton_24.raise_()
        self.radioButton_25.raise_()
        self.radioButton_26.raise_()
        self.radioButton_27.raise_()
        self.radioButton_28.raise_()
        self.radioButton_29.raise_()
        self.radioButton_30.raise_()
        self.radioButton_31.raise_()
        self.radioButton_32.raise_()
        self.radioButton_33.raise_()
        self.radioButton_34.raise_()
        self.radioButton_35.raise_()
        self.radioButton_36.raise_()
        self.radioButton_37.raise_()
        self.radioButton_38.raise_()
        self.radioButton_39.raise_()
        self.radioButton_40.raise_()
        self.radioButton_41.raise_()
        self.radioButton_42.raise_()
        self.radioButton_43.raise_()
        self.radioButton_44.raise_()
        self.radioButton_20.raise_()
        self.wave2GenBtn.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_8.raise_()
        self.stackedWidget.addWidget(self.wave2Page1)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.gridLayout.addWidget(self.stackedWidget, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 0, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.nameLabel.setBuddy(self.nameEdit)
        self.raceLabel.setBuddy(self.raceBox)
        self.classLabel.setBuddy(self.classBox)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Session Zero"))
        self.titleLabel.setText(_translate("MainWindow", "Session Zero"))
        self.buildBtn.setText(_translate("MainWindow", "Build a Character"))
        self.loadBtn.setText(_translate("MainWindow", "Load a Character"))
        self.nameLabel.setText(_translate("MainWindow", "Name:"))
        self.raceLabel.setText(_translate("MainWindow", "Race:"))
        self.raceBox.setItemText(0, _translate("MainWindow", "Dwarf"))
        self.raceBox.setItemText(1, _translate("MainWindow", "Halfling"))
        self.raceBox.setItemText(2, _translate("MainWindow", "Elf"))
        self.raceBox.setItemText(3, _translate("MainWindow", "Human"))
        self.raceBox.setItemText(4, _translate("MainWindow", "Gnome"))
        self.raceBox.setItemText(5, _translate("MainWindow", "Half-orc"))
        self.raceBox.setItemText(6, _translate("MainWindow", "Half-elf"))
        self.classLabel.setText(_translate("MainWindow", "Class: "))
        self.classBox.setItemText(0, _translate("MainWindow", "Adept"))
        self.classBox.setItemText(1, _translate("MainWindow", "Aristocrat"))
        self.classBox.setItemText(2, _translate("MainWindow", "Barbarian"))
        self.classBox.setItemText(3, _translate("MainWindow", "Bard"))
        self.classBox.setItemText(4, _translate("MainWindow", "Cleric"))
        self.classBox.setItemText(5, _translate("MainWindow", "Commoner"))
        self.classBox.setItemText(6, _translate("MainWindow", "Druid"))
        self.classBox.setItemText(7, _translate("MainWindow", "Expert"))
        self.classBox.setItemText(8, _translate("MainWindow", "Fighter"))
        self.classBox.setItemText(9, _translate("MainWindow", "Monk"))
        self.classBox.setItemText(10, _translate("MainWindow", "Paladin"))
        self.classBox.setItemText(11, _translate("MainWindow", "Ranger"))
        self.classBox.setItemText(12, _translate("MainWindow", "Rogue"))
        self.classBox.setItemText(13, _translate("MainWindow", "Sorcerer"))
        self.classBox.setItemText(14, _translate("MainWindow", "Warrior"))
        self.classBox.setItemText(15, _translate("MainWindow", "Wizard"))
        self.statsPlusLabel.setText(_translate("MainWindow", "Quantitative Strengths:"))
        self.statsMinusLabel.setText(_translate("MainWindow", "Quantitative Weaknesses:"))
        self.checkBox_2.setText(_translate("MainWindow", "Strong"))
        self.checkBox_3.setText(_translate("MainWindow", "Quick"))
        self.checkBox_4.setText(_translate("MainWindow", "Hardy"))
        self.checkBox_5.setText(_translate("MainWindow", "Intelligent"))
        self.checkBox_6.setText(_translate("MainWindow", "Charismatic"))
        self.checkBox.setText(_translate("MainWindow", "Wise"))
        self.checkBox_8.setText(_translate("MainWindow", "Weak"))
        self.checkBox_11.setText(_translate("MainWindow", "Slow"))
        self.checkBox_10.setText(_translate("MainWindow", "Frail"))
        self.checkBox_12.setText(_translate("MainWindow", "Stupid"))
        self.checkBox_9.setText(_translate("MainWindow", "Unmannered"))
        self.checkBox_7.setText(_translate("MainWindow", "Imprudent"))
        self.wave1GenBtn.setText(_translate("MainWindow", "Generate Statblock"))
        self.wave1Label.setText(_translate("MainWindow", "Basic Character Information"))
        self.selectBtn2.setText(_translate("MainWindow", "Select"))
        self.selectBtn3.setText(_translate("MainWindow", "Select"))
        self.selectBtn1.setText(_translate("MainWindow", "Select"))
        item = self.statblock1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stat"))
        item = self.statblock1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.statblock1.isSortingEnabled()
        self.statblock1.setSortingEnabled(False)
        item = self.statblock1.item(0, 0)
        item.setText(_translate("MainWindow", "Strength"))
        item = self.statblock1.item(1, 0)
        item.setText(_translate("MainWindow", "Dexterity"))
        item = self.statblock1.item(2, 0)
        item.setText(_translate("MainWindow", "Constitution"))
        item = self.statblock1.item(3, 0)
        item.setText(_translate("MainWindow", "Intelligence"))
        item = self.statblock1.item(4, 0)
        item.setText(_translate("MainWindow", "Wisdom"))
        item = self.statblock1.item(5, 0)
        item.setText(_translate("MainWindow", "Charisma"))
        self.statblock1.setSortingEnabled(__sortingEnabled)
        item = self.statblock2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stat"))
        item = self.statblock2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.statblock2.isSortingEnabled()
        self.statblock2.setSortingEnabled(False)
        item = self.statblock2.item(0, 0)
        item.setText(_translate("MainWindow", "Strength"))
        item = self.statblock2.item(1, 0)
        item.setText(_translate("MainWindow", "Dexterity"))
        item = self.statblock2.item(2, 0)
        item.setText(_translate("MainWindow", "Constitution"))
        item = self.statblock2.item(3, 0)
        item.setText(_translate("MainWindow", "Intelligence"))
        item = self.statblock2.item(4, 0)
        item.setText(_translate("MainWindow", "Wisdom"))
        item = self.statblock2.item(5, 0)
        item.setText(_translate("MainWindow", "Charisma"))
        self.statblock2.setSortingEnabled(__sortingEnabled)
        item = self.statblock3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stat"))
        item = self.statblock3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.statblock3.isSortingEnabled()
        self.statblock3.setSortingEnabled(False)
        item = self.statblock3.item(0, 0)
        item.setText(_translate("MainWindow", "Strength"))
        item = self.statblock3.item(1, 0)
        item.setText(_translate("MainWindow", "Dexterity"))
        item = self.statblock3.item(2, 0)
        item.setText(_translate("MainWindow", "Constitution"))
        item = self.statblock3.item(3, 0)
        item.setText(_translate("MainWindow", "Intelligence"))
        item = self.statblock3.item(4, 0)
        item.setText(_translate("MainWindow", "Wisdom"))
        item = self.statblock3.item(5, 0)
        item.setText(_translate("MainWindow", "Charisma"))
        self.statblock3.setSortingEnabled(__sortingEnabled)
        self.wave1EndBtn.setText(_translate("MainWindow", "Continue"))
        self.statblockLabel.setText(_translate("MainWindow", "Select the statblock that fits your character best"))
        self.genLabel.setText(_translate("MainWindow", "Basic Character Information"))
        self.radioButton_27.setText(_translate("MainWindow", "Sycophantic"))
        self.radioButton_25.setText(_translate("MainWindow", "Friendly"))
        self.radioButton_15.setText(_translate("MainWindow", "Insensible"))
        self.radioButton_16.setText(_translate("MainWindow", "Caring"))
        self.radioButton_19.setText(_translate("MainWindow", "Modest"))
        self.radioButton_21.setText(_translate("MainWindow", "Shy"))
        self.radioButton_17.setText(_translate("MainWindow", "Aloof"))
        self.radioButton_20.setText(_translate("MainWindow", "Shameless"))
        self.radioButton_24.setText(_translate("MainWindow", "Foolish"))
        self.radioButton_18.setText(_translate("MainWindow", "Empathetic"))
        self.radioButton_22.setText(_translate("MainWindow", "Witty"))
        self.radioButton_23.setText(_translate("MainWindow", "Boorish"))
        self.radioButton_35.setText(_translate("MainWindow", "Unambitious"))
        self.radioButton_26.setText(_translate("MainWindow", "Independent"))
        self.radioButton_37.setText(_translate("MainWindow", "Brave"))
        self.radioButton_41.setText(_translate("MainWindow", "Miserly"))
        self.radioButton_33.setText(_translate("MainWindow", "Wrathful"))
        self.radioButton_40.setText(_translate("MainWindow", "Reserved"))
        self.radioButton_31.setText(_translate("MainWindow", "Patient"))
        self.radioButton_29.setText(_translate("MainWindow", "Understated"))
        self.radioButton_36.setText(_translate("MainWindow", "Self-absorbed"))
        self.radioButton_39.setText(_translate("MainWindow", "Rash"))
        self.radioButton_32.setText(_translate("MainWindow", "Numb"))
        self.radioButton_28.setText(_translate("MainWindow", "Honest"))
        self.wave2GenBtn.setText(_translate("MainWindow", "Generate Additional Traits"))
        self.radioButton_30.setText(_translate("MainWindow", "Boastful"))
        self.radioButton_34.setText(_translate("MainWindow", "Humble"))
        self.radioButton_38.setText(_translate("MainWindow", "Cowardly"))
        self.radioButton_42.setText(_translate("MainWindow", "Ostentatious"))
        self.radioButton_5.setText(_translate("MainWindow", "Curiosity"))
        self.radioButton_44.setText(_translate("MainWindow", "Creativity"))
        self.grtWkLabel.setText(_translate("MainWindow", "Greatest Weakness:"))
        self.radioButton_6.setText(_translate("MainWindow", "Anger"))
        self.radioButton.setText(_translate("MainWindow", "Loyalty"))
        self.grtStrLabel.setText(_translate("MainWindow", "Greatest Strength:"))
        self.radioButton_2.setText(_translate("MainWindow", "Compassion"))
        self.radioButton_3.setText(_translate("MainWindow", "Discipline"))
        self.radioButton_4.setText(_translate("MainWindow", "Humility"))
        self.radioButton_11.setText(_translate("MainWindow", "Tolerance"))
        self.radioButton_8.setText(_translate("MainWindow", "Insecurity"))
        self.traitsLabel.setText(_translate("MainWindow", "What traits does your character possess?"))
        self.radioButton_9.setText(_translate("MainWindow", "Laziness"))
        self.radioButton_12.setText(_translate("MainWindow", "Pride"))
        self.radioButton_43.setText(_translate("MainWindow", "Envy"))
        self.radioButton_13.setText(_translate("MainWindow", "Indulgent"))
        self.radioButton_14.setText(_translate("MainWindow", "Restrained"))
        self.radioButton_10.setText(_translate("MainWindow", "Lust"))
        self.radioButton_7.setText(_translate("MainWindow", "Greed"))
        self.wave2Label.setText(_translate("MainWindow", "Personality Traits"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

