# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'session-zero.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 772)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.page)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout_2.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.buildBtn = QtWidgets.QPushButton(self.page)
        self.buildBtn.setObjectName("buildBtn")
        self.gridLayout_2.addWidget(self.buildBtn, 3, 0, 1, 1)
        self.loadBtn = QtWidgets.QPushButton(self.page)
        self.loadBtn.setObjectName("loadBtn")
        self.gridLayout_2.addWidget(self.loadBtn, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 4, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.page)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.nameEdit = QtWidgets.QLineEdit(self.page_2)
        self.nameEdit.setMaxLength(25)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_3.addWidget(self.nameEdit, 3, 1, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.page_2)
        self.nameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_3.addWidget(self.nameLabel, 3, 0, 1, 1)
        self.raceLabel = QtWidgets.QLabel(self.page_2)
        self.raceLabel.setObjectName("raceLabel")
        self.gridLayout_3.addWidget(self.raceLabel, 4, 0, 1, 1)
        self.raceBox = QtWidgets.QComboBox(self.page_2)
        self.raceBox.setObjectName("raceBox")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.gridLayout_3.addWidget(self.raceBox, 4, 1, 1, 1)
        self.classLabel = QtWidgets.QLabel(self.page_2)
        self.classLabel.setObjectName("classLabel")
        self.gridLayout_3.addWidget(self.classLabel, 5, 0, 1, 1)
        self.classBox = QtWidgets.QComboBox(self.page_2)
        self.classBox.setObjectName("classBox")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.gridLayout_3.addWidget(self.classBox, 5, 1, 1, 1)
        self.wave1Label = QtWidgets.QLabel(self.page_2)
        self.wave1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.wave1Label.setObjectName("wave1Label")
        self.gridLayout_3.addWidget(self.wave1Label, 1, 0, 1, 2)
        self.statsPlusLabel = QtWidgets.QLabel(self.page_2)
        self.statsPlusLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.statsPlusLabel.setObjectName("statsPlusLabel")
        self.gridLayout_3.addWidget(self.statsPlusLabel, 6, 0, 1, 1)
        self.statsMinusLabel = QtWidgets.QLabel(self.page_2)
        self.statsMinusLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.statsMinusLabel.setObjectName("statsMinusLabel")
        self.gridLayout_3.addWidget(self.statsMinusLabel, 7, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.statPlusGroup = QtWidgets.QButtonGroup(MainWindow)
        self.statPlusGroup.setObjectName("statPlusGroup")
        self.statPlusGroup.setExclusive(False)
        self.statPlusGroup.addButton(self.checkBox_2)
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.statPlusGroup.addButton(self.checkBox_3)
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.statPlusGroup.addButton(self.checkBox_4)
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.statPlusGroup.addButton(self.checkBox_5)
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.statPlusGroup.addButton(self.checkBox_6)
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox = QtWidgets.QCheckBox(self.page_2)
        self.checkBox.setObjectName("checkBox")
        self.statPlusGroup.addButton(self.checkBox)
        self.verticalLayout.addWidget(self.checkBox)
        self.gridLayout_3.addLayout(self.verticalLayout, 6, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_8 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_8.setObjectName("checkBox_8")
        self.statMinusGroup = QtWidgets.QButtonGroup(MainWindow)
        self.statMinusGroup.setObjectName("statMinusGroup")
        self.statMinusGroup.setExclusive(False)
        self.statMinusGroup.addButton(self.checkBox_8)
        self.verticalLayout_2.addWidget(self.checkBox_8)
        self.checkBox_11 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_11.setObjectName("checkBox_11")
        self.statMinusGroup.addButton(self.checkBox_11)
        self.verticalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_10 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_10.setObjectName("checkBox_10")
        self.statMinusGroup.addButton(self.checkBox_10)
        self.verticalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_12 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_12.setObjectName("checkBox_12")
        self.statMinusGroup.addButton(self.checkBox_12)
        self.verticalLayout_2.addWidget(self.checkBox_12)
        self.checkBox_9 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_9.setObjectName("checkBox_9")
        self.statMinusGroup.addButton(self.checkBox_9)
        self.verticalLayout_2.addWidget(self.checkBox_9)
        self.checkBox_7 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_7.setObjectName("checkBox_7")
        self.statMinusGroup.addButton(self.checkBox_7)
        self.verticalLayout_2.addWidget(self.checkBox_7)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 7, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.page_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 2, 0, 1, 2)
        self.wave1GenBtn = QtWidgets.QPushButton(self.page_2)
        self.wave1GenBtn.setObjectName("wave1GenBtn")
        self.gridLayout_3.addWidget(self.wave1GenBtn, 8, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.selectBtn2 = QtWidgets.QRadioButton(self.page_3)
        self.selectBtn2.setObjectName("selectBtn2")
        self.statblockGroup = QtWidgets.QButtonGroup(MainWindow)
        self.statblockGroup.setObjectName("statblockGroup")
        self.statblockGroup.addButton(self.selectBtn2)
        self.gridLayout_4.addWidget(self.selectBtn2, 3, 0, 1, 1)
        self.selectBtn3 = QtWidgets.QRadioButton(self.page_3)
        self.selectBtn3.setObjectName("selectBtn3")
        self.statblockGroup.addButton(self.selectBtn3)
        self.gridLayout_4.addWidget(self.selectBtn3, 4, 0, 1, 1)
        self.selectBtn1 = QtWidgets.QRadioButton(self.page_3)
        self.selectBtn1.setChecked(True)
        self.selectBtn1.setObjectName("selectBtn1")
        self.statblockGroup.addButton(self.selectBtn1)
        self.gridLayout_4.addWidget(self.selectBtn1, 2, 0, 1, 1)
        self.statblock1 = QtWidgets.QTableWidget(self.page_3)
        self.statblock1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.statblock1.setRowCount(6)
        self.statblock1.setColumnCount(2)
        self.statblock1.setObjectName("statblock1")
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(5, 0, item)
        self.statblock1.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.statblock1, 2, 1, 1, 1)
        self.statblock2 = QtWidgets.QTableWidget(self.page_3)
        self.statblock2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.statblock2.setRowCount(6)
        self.statblock2.setColumnCount(2)
        self.statblock2.setObjectName("statblock2")
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(5, 0, item)
        self.statblock2.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.statblock2, 3, 1, 1, 1)
        self.statblock3 = QtWidgets.QTableWidget(self.page_3)
        self.statblock3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.statblock3.setRowCount(6)
        self.statblock3.setColumnCount(2)
        self.statblock3.setObjectName("statblock3")
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(5, 0, item)
        self.statblock3.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.statblock3, 4, 1, 1, 1)
        self.genLabel = QtWidgets.QLabel(self.page_3)
        self.genLabel.setObjectName("genLabel")
        self.gridLayout_4.addWidget(self.genLabel, 0, 1, 1, 1)
        self.statblockLabel = QtWidgets.QLabel(self.page_3)
        self.statblockLabel.setObjectName("statblockLabel")
        self.gridLayout_4.addWidget(self.statblockLabel, 1, 0, 1, 2)
        self.wave1EndBtn = QtWidgets.QPushButton(self.page_3)
        self.wave1EndBtn.setObjectName("wave1EndBtn")
        self.gridLayout_4.addWidget(self.wave1EndBtn, 5, 1, 1, 1)
        self.statblockLabel.raise_()
        self.genLabel.raise_()
        self.statblock1.raise_()
        self.statblock2.raise_()
        self.statblock3.raise_()
        self.selectBtn1.raise_()
        self.selectBtn2.raise_()
        self.selectBtn3.raise_()
        self.wave1EndBtn.raise_()
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.nameLabel.setBuddy(self.nameEdit)
        self.raceLabel.setBuddy(self.raceBox)
        self.classLabel.setBuddy(self.classBox)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Session Zero"))
        self.titleLabel.setText(_translate("MainWindow", "Session Zero"))
        self.buildBtn.setText(_translate("MainWindow", "Build a Character"))
        self.loadBtn.setText(_translate("MainWindow", "Load a Character"))
        self.nameLabel.setText(_translate("MainWindow", "Name:"))
        self.raceLabel.setText(_translate("MainWindow", "Race:"))
        self.raceBox.setItemText(0, _translate("MainWindow", "Dwarf"))
        self.raceBox.setItemText(1, _translate("MainWindow", "Halfling"))
        self.raceBox.setItemText(2, _translate("MainWindow", "Elf"))
        self.raceBox.setItemText(3, _translate("MainWindow", "Human"))
        self.raceBox.setItemText(4, _translate("MainWindow", "Gnome"))
        self.raceBox.setItemText(5, _translate("MainWindow", "Half-orc"))
        self.raceBox.setItemText(6, _translate("MainWindow", "Half-elf"))
        self.classLabel.setText(_translate("MainWindow", "Class: "))
        self.classBox.setItemText(0, _translate("MainWindow", "Adept"))
        self.classBox.setItemText(1, _translate("MainWindow", "Aristocrat"))
        self.classBox.setItemText(2, _translate("MainWindow", "Barbarian"))
        self.classBox.setItemText(3, _translate("MainWindow", "Bard"))
        self.classBox.setItemText(4, _translate("MainWindow", "Cleric"))
        self.classBox.setItemText(5, _translate("MainWindow", "Commoner"))
        self.classBox.setItemText(6, _translate("MainWindow", "Druid"))
        self.classBox.setItemText(7, _translate("MainWindow", "Expert"))
        self.classBox.setItemText(8, _translate("MainWindow", "Fighter"))
        self.classBox.setItemText(9, _translate("MainWindow", "Monk"))
        self.classBox.setItemText(10, _translate("MainWindow", "Paladin"))
        self.classBox.setItemText(11, _translate("MainWindow", "Ranger"))
        self.classBox.setItemText(12, _translate("MainWindow", "Rogue"))
        self.classBox.setItemText(13, _translate("MainWindow", "Sorcerer"))
        self.classBox.setItemText(14, _translate("MainWindow", "Warrior"))
        self.classBox.setItemText(15, _translate("MainWindow", "Wizard"))
        self.wave1Label.setText(_translate("MainWindow", "Basic Character Information"))
        self.statsPlusLabel.setText(_translate("MainWindow", "Quantitative Strengths:"))
        self.statsMinusLabel.setText(_translate("MainWindow", "Quantitative Weaknesses:"))
        self.checkBox_2.setText(_translate("MainWindow", "Strong"))
        self.checkBox_3.setText(_translate("MainWindow", "Quick"))
        self.checkBox_4.setText(_translate("MainWindow", "Hardy"))
        self.checkBox_5.setText(_translate("MainWindow", "Intelligent"))
        self.checkBox_6.setText(_translate("MainWindow", "Charismatic"))
        self.checkBox.setText(_translate("MainWindow", "Wise"))
        self.checkBox_8.setText(_translate("MainWindow", "Weak"))
        self.checkBox_11.setText(_translate("MainWindow", "Slow"))
        self.checkBox_10.setText(_translate("MainWindow", "Frail"))
        self.checkBox_12.setText(_translate("MainWindow", "Stupid"))
        self.checkBox_9.setText(_translate("MainWindow", "Unmannered"))
        self.checkBox_7.setText(_translate("MainWindow", "Imprudent"))
        self.wave1GenBtn.setText(_translate("MainWindow", "Generate Statblock"))
        self.selectBtn2.setText(_translate("MainWindow", "Select"))
        self.selectBtn3.setText(_translate("MainWindow", "Select"))
        self.selectBtn1.setText(_translate("MainWindow", "Select"))
        item = self.statblock1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stat"))
        item = self.statblock1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.statblock1.isSortingEnabled()
        self.statblock1.setSortingEnabled(False)
        item = self.statblock1.item(0, 0)
        item.setText(_translate("MainWindow", "Strength"))
        item = self.statblock1.item(1, 0)
        item.setText(_translate("MainWindow", "Dexterity"))
        item = self.statblock1.item(2, 0)
        item.setText(_translate("MainWindow", "Constitution"))
        item = self.statblock1.item(3, 0)
        item.setText(_translate("MainWindow", "Intelligence"))
        item = self.statblock1.item(4, 0)
        item.setText(_translate("MainWindow", "Wisdom"))
        item = self.statblock1.item(5, 0)
        item.setText(_translate("MainWindow", "Charisma"))
        self.statblock1.setSortingEnabled(__sortingEnabled)
        item = self.statblock2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stat"))
        item = self.statblock2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.statblock2.isSortingEnabled()
        self.statblock2.setSortingEnabled(False)
        item = self.statblock2.item(0, 0)
        item.setText(_translate("MainWindow", "Strength"))
        item = self.statblock2.item(1, 0)
        item.setText(_translate("MainWindow", "Dexterity"))
        item = self.statblock2.item(2, 0)
        item.setText(_translate("MainWindow", "Constitution"))
        item = self.statblock2.item(3, 0)
        item.setText(_translate("MainWindow", "Intelligence"))
        item = self.statblock2.item(4, 0)
        item.setText(_translate("MainWindow", "Wisdom"))
        item = self.statblock2.item(5, 0)
        item.setText(_translate("MainWindow", "Charisma"))
        self.statblock2.setSortingEnabled(__sortingEnabled)
        item = self.statblock3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stat"))
        item = self.statblock3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.statblock3.isSortingEnabled()
        self.statblock3.setSortingEnabled(False)
        item = self.statblock3.item(0, 0)
        item.setText(_translate("MainWindow", "Strength"))
        item = self.statblock3.item(1, 0)
        item.setText(_translate("MainWindow", "Dexterity"))
        item = self.statblock3.item(2, 0)
        item.setText(_translate("MainWindow", "Constitution"))
        item = self.statblock3.item(3, 0)
        item.setText(_translate("MainWindow", "Intelligence"))
        item = self.statblock3.item(4, 0)
        item.setText(_translate("MainWindow", "Wisdom"))
        item = self.statblock3.item(5, 0)
        item.setText(_translate("MainWindow", "Charisma"))
        self.statblock3.setSortingEnabled(__sortingEnabled)
        self.genLabel.setText(_translate("MainWindow", "Basic Character Information"))
        self.statblockLabel.setText(_translate("MainWindow", "Select the statblock that fits your character best"))
        self.wave1EndBtn.setText(_translate("MainWindow", "Continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

