# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'session-zero.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 772)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.startPage = QtWidgets.QWidget()
        self.startPage.setObjectName("startPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.startPage)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.startPage)
        self.titleLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout_2.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.buildBtn = QtWidgets.QPushButton(self.startPage)
        self.buildBtn.setObjectName("buildBtn")
        self.gridLayout_2.addWidget(self.buildBtn, 3, 0, 1, 1)
        self.loadBtn = QtWidgets.QPushButton(self.startPage)
        self.loadBtn.setObjectName("loadBtn")
        self.gridLayout_2.addWidget(self.loadBtn, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.startPage)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.startPage)
        self.wave1Page1 = QtWidgets.QWidget()
        self.wave1Page1.setObjectName("wave1Page1")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.wave1Page1)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.wave1Label = QtWidgets.QLabel(self.wave1Page1)
        self.wave1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.wave1Label.setObjectName("wave1Label")
        self.gridLayout_15.addWidget(self.wave1Label, 0, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.wave1Page1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_15.addWidget(self.line_2, 1, 0, 1, 2)
        self.nameLabel = QtWidgets.QLabel(self.wave1Page1)
        self.nameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_15.addWidget(self.nameLabel, 2, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(self.wave1Page1)
        self.nameEdit.setMaxLength(25)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_15.addWidget(self.nameEdit, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem3, 3, 0, 1, 1)
        self.raceLabel = QtWidgets.QLabel(self.wave1Page1)
        self.raceLabel.setObjectName("raceLabel")
        self.gridLayout_15.addWidget(self.raceLabel, 4, 0, 1, 1)
        self.raceBox = QtWidgets.QComboBox(self.wave1Page1)
        self.raceBox.setObjectName("raceBox")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.raceBox.addItem("")
        self.gridLayout_15.addWidget(self.raceBox, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem4, 5, 0, 1, 1)
        self.classLabel = QtWidgets.QLabel(self.wave1Page1)
        self.classLabel.setObjectName("classLabel")
        self.gridLayout_15.addWidget(self.classLabel, 6, 0, 1, 1)
        self.classBox = QtWidgets.QComboBox(self.wave1Page1)
        self.classBox.setObjectName("classBox")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.gridLayout_15.addWidget(self.classBox, 6, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem5, 7, 0, 1, 1)
        self.statsPlusLabel = QtWidgets.QLabel(self.wave1Page1)
        self.statsPlusLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.statsPlusLabel.setObjectName("statsPlusLabel")
        self.gridLayout_15.addWidget(self.statsPlusLabel, 8, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_2 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_2.setObjectName("checkBox_2")
        self.statPlusGroup = QtWidgets.QButtonGroup(MainWindow)
        self.statPlusGroup.setObjectName("statPlusGroup")
        self.statPlusGroup.setExclusive(False)
        self.statPlusGroup.addButton(self.checkBox_2)
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_3.setObjectName("checkBox_3")
        self.statPlusGroup.addButton(self.checkBox_3)
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_4.setObjectName("checkBox_4")
        self.statPlusGroup.addButton(self.checkBox_4)
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_5.setObjectName("checkBox_5")
        self.statPlusGroup.addButton(self.checkBox_5)
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox.setObjectName("checkBox")
        self.statPlusGroup.addButton(self.checkBox)
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_6 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_6.setObjectName("checkBox_6")
        self.statPlusGroup.addButton(self.checkBox_6)
        self.verticalLayout.addWidget(self.checkBox_6)
        self.gridLayout_15.addLayout(self.verticalLayout, 8, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem6, 9, 0, 1, 1)
        self.statsMinusLabel = QtWidgets.QLabel(self.wave1Page1)
        self.statsMinusLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.statsMinusLabel.setObjectName("statsMinusLabel")
        self.gridLayout_15.addWidget(self.statsMinusLabel, 10, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_8 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_8.setObjectName("checkBox_8")
        self.statMinusGroup = QtWidgets.QButtonGroup(MainWindow)
        self.statMinusGroup.setObjectName("statMinusGroup")
        self.statMinusGroup.setExclusive(False)
        self.statMinusGroup.addButton(self.checkBox_8)
        self.verticalLayout_2.addWidget(self.checkBox_8)
        self.checkBox_11 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_11.setObjectName("checkBox_11")
        self.statMinusGroup.addButton(self.checkBox_11)
        self.verticalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_10 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_10.setObjectName("checkBox_10")
        self.statMinusGroup.addButton(self.checkBox_10)
        self.verticalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_12 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_12.setObjectName("checkBox_12")
        self.statMinusGroup.addButton(self.checkBox_12)
        self.verticalLayout_2.addWidget(self.checkBox_12)
        self.checkBox_7 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_7.setObjectName("checkBox_7")
        self.statMinusGroup.addButton(self.checkBox_7)
        self.verticalLayout_2.addWidget(self.checkBox_7)
        self.checkBox_9 = QtWidgets.QCheckBox(self.wave1Page1)
        self.checkBox_9.setObjectName("checkBox_9")
        self.statMinusGroup.addButton(self.checkBox_9)
        self.verticalLayout_2.addWidget(self.checkBox_9)
        self.gridLayout_15.addLayout(self.verticalLayout_2, 10, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem7, 11, 1, 1, 1)
        self.wave1GenBtn = QtWidgets.QPushButton(self.wave1Page1)
        self.wave1GenBtn.setObjectName("wave1GenBtn")
        self.gridLayout_15.addWidget(self.wave1GenBtn, 12, 0, 1, 2)
        self.stackedWidget.addWidget(self.wave1Page1)
        self.wave1Results = QtWidgets.QWidget()
        self.wave1Results.setObjectName("wave1Results")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.wave1Results)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.statblock2 = QtWidgets.QTableWidget(self.wave1Results)
        self.statblock2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.statblock2.setRowCount(6)
        self.statblock2.setColumnCount(2)
        self.statblock2.setObjectName("statblock2")
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock2.setItem(5, 0, item)
        self.statblock2.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.statblock2, 4, 1, 1, 1)
        self.selectBtn3 = QtWidgets.QRadioButton(self.wave1Results)
        self.selectBtn3.setObjectName("selectBtn3")
        self.statblockGroup = QtWidgets.QButtonGroup(MainWindow)
        self.statblockGroup.setObjectName("statblockGroup")
        self.statblockGroup.addButton(self.selectBtn3)
        self.gridLayout_4.addWidget(self.selectBtn3, 5, 0, 1, 1)
        self.statblock3 = QtWidgets.QTableWidget(self.wave1Results)
        self.statblock3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.statblock3.setRowCount(6)
        self.statblock3.setColumnCount(2)
        self.statblock3.setObjectName("statblock3")
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock3.setItem(5, 0, item)
        self.statblock3.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.statblock3, 5, 1, 1, 1)
        self.genLabel = QtWidgets.QLabel(self.wave1Results)
        self.genLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.genLabel.setObjectName("genLabel")
        self.gridLayout_4.addWidget(self.genLabel, 0, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.wave1Results)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 1, 0, 1, 2)
        self.statblockLabel = QtWidgets.QLabel(self.wave1Results)
        self.statblockLabel.setObjectName("statblockLabel")
        self.gridLayout_4.addWidget(self.statblockLabel, 2, 0, 1, 2)
        self.selectBtn1 = QtWidgets.QRadioButton(self.wave1Results)
        self.selectBtn1.setChecked(True)
        self.selectBtn1.setObjectName("selectBtn1")
        self.statblockGroup.addButton(self.selectBtn1)
        self.gridLayout_4.addWidget(self.selectBtn1, 3, 0, 1, 1)
        self.statblock1 = QtWidgets.QTableWidget(self.wave1Results)
        self.statblock1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.statblock1.setRowCount(6)
        self.statblock1.setColumnCount(2)
        self.statblock1.setObjectName("statblock1")
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statblock1.setItem(5, 0, item)
        self.statblock1.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.statblock1, 3, 1, 1, 1)
        self.selectBtn2 = QtWidgets.QRadioButton(self.wave1Results)
        self.selectBtn2.setObjectName("selectBtn2")
        self.statblockGroup.addButton(self.selectBtn2)
        self.gridLayout_4.addWidget(self.selectBtn2, 4, 0, 1, 1)
        self.wave1EndBtn = QtWidgets.QPushButton(self.wave1Results)
        self.wave1EndBtn.setObjectName("wave1EndBtn")
        self.gridLayout_4.addWidget(self.wave1EndBtn, 6, 0, 1, 2)
        self.statblockLabel.raise_()
        self.genLabel.raise_()
        self.statblock1.raise_()
        self.statblock2.raise_()
        self.statblock3.raise_()
        self.selectBtn1.raise_()
        self.selectBtn2.raise_()
        self.selectBtn3.raise_()
        self.wave1EndBtn.raise_()
        self.line_3.raise_()
        self.stackedWidget.addWidget(self.wave1Results)
        self.wave2Page1 = QtWidgets.QWidget()
        self.wave2Page1.setObjectName("wave2Page1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.wave2Page1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line_4 = QtWidgets.QFrame(self.wave2Page1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_5.addWidget(self.line_4, 1, 0, 1, 3)
        self.line_5 = QtWidgets.QFrame(self.wave2Page1)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_5.addWidget(self.line_5, 17, 0, 1, 3)
        self.radioButton_27 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_27.setObjectName("radioButton_27")
        self.friendGroup = QtWidgets.QButtonGroup(MainWindow)
        self.friendGroup.setObjectName("friendGroup")
        self.friendGroup.addButton(self.radioButton_27)
        self.gridLayout_5.addWidget(self.radioButton_27, 23, 0, 1, 1)
        self.radioButton_25 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_25.setObjectName("radioButton_25")
        self.friendGroup.addButton(self.radioButton_25)
        self.gridLayout_5.addWidget(self.radioButton_25, 23, 1, 1, 1)
        self.radioButton_15 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_15.setObjectName("radioButton_15")
        self.senseGroup = QtWidgets.QButtonGroup(MainWindow)
        self.senseGroup.setObjectName("senseGroup")
        self.senseGroup.addButton(self.radioButton_15)
        self.gridLayout_5.addWidget(self.radioButton_15, 19, 2, 1, 1)
        self.radioButton_16 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_16.setObjectName("radioButton_16")
        self.careGroup = QtWidgets.QButtonGroup(MainWindow)
        self.careGroup.setObjectName("careGroup")
        self.careGroup.addButton(self.radioButton_16)
        self.gridLayout_5.addWidget(self.radioButton_16, 20, 1, 1, 1)
        self.radioButton_19 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_19.setObjectName("radioButton_19")
        self.modestGroup = QtWidgets.QButtonGroup(MainWindow)
        self.modestGroup.setObjectName("modestGroup")
        self.modestGroup.addButton(self.radioButton_19)
        self.gridLayout_5.addWidget(self.radioButton_19, 21, 1, 1, 1)
        self.radioButton_21 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_21.setObjectName("radioButton_21")
        self.modestGroup.addButton(self.radioButton_21)
        self.gridLayout_5.addWidget(self.radioButton_21, 21, 2, 1, 1)
        self.radioButton_17 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_17.setObjectName("radioButton_17")
        self.careGroup.addButton(self.radioButton_17)
        self.gridLayout_5.addWidget(self.radioButton_17, 20, 2, 1, 1)
        self.radioButton_20 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_20.setObjectName("radioButton_20")
        self.modestGroup.addButton(self.radioButton_20)
        self.gridLayout_5.addWidget(self.radioButton_20, 21, 0, 1, 1)
        self.radioButton_24 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_24.setObjectName("radioButton_24")
        self.witGroup = QtWidgets.QButtonGroup(MainWindow)
        self.witGroup.setObjectName("witGroup")
        self.witGroup.addButton(self.radioButton_24)
        self.gridLayout_5.addWidget(self.radioButton_24, 22, 0, 1, 1)
        self.radioButton_18 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_18.setObjectName("radioButton_18")
        self.careGroup.addButton(self.radioButton_18)
        self.gridLayout_5.addWidget(self.radioButton_18, 20, 0, 1, 1)
        self.radioButton_22 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_22.setObjectName("radioButton_22")
        self.witGroup.addButton(self.radioButton_22)
        self.gridLayout_5.addWidget(self.radioButton_22, 22, 1, 1, 1)
        self.radioButton_23 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_23.setObjectName("radioButton_23")
        self.witGroup.addButton(self.radioButton_23)
        self.gridLayout_5.addWidget(self.radioButton_23, 22, 2, 1, 1)
        self.radioButton_35 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_35.setObjectName("radioButton_35")
        self.humbleGroup = QtWidgets.QButtonGroup(MainWindow)
        self.humbleGroup.setObjectName("humbleGroup")
        self.humbleGroup.addButton(self.radioButton_35)
        self.gridLayout_5.addWidget(self.radioButton_35, 26, 2, 1, 1)
        self.radioButton_26 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_26.setObjectName("radioButton_26")
        self.friendGroup.addButton(self.radioButton_26)
        self.gridLayout_5.addWidget(self.radioButton_26, 23, 2, 1, 1)
        self.radioButton_37 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_37.setObjectName("radioButton_37")
        self.braveGroup = QtWidgets.QButtonGroup(MainWindow)
        self.braveGroup.setObjectName("braveGroup")
        self.braveGroup.addButton(self.radioButton_37)
        self.gridLayout_5.addWidget(self.radioButton_37, 27, 1, 1, 1)
        self.radioButton_41 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_41.setObjectName("radioButton_41")
        self.moneyGroup = QtWidgets.QButtonGroup(MainWindow)
        self.moneyGroup.setObjectName("moneyGroup")
        self.moneyGroup.addButton(self.radioButton_41)
        self.gridLayout_5.addWidget(self.radioButton_41, 28, 2, 1, 1)
        self.radioButton_33 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_33.setObjectName("radioButton_33")
        self.patientGroup = QtWidgets.QButtonGroup(MainWindow)
        self.patientGroup.setObjectName("patientGroup")
        self.patientGroup.addButton(self.radioButton_33)
        self.gridLayout_5.addWidget(self.radioButton_33, 25, 0, 1, 1)
        self.radioButton_40 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_40.setObjectName("radioButton_40")
        self.moneyGroup.addButton(self.radioButton_40)
        self.gridLayout_5.addWidget(self.radioButton_40, 28, 1, 1, 1)
        self.radioButton_31 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_31.setObjectName("radioButton_31")
        self.patientGroup.addButton(self.radioButton_31)
        self.gridLayout_5.addWidget(self.radioButton_31, 25, 1, 1, 1)
        self.radioButton_29 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_29.setObjectName("radioButton_29")
        self.honestGroup = QtWidgets.QButtonGroup(MainWindow)
        self.honestGroup.setObjectName("honestGroup")
        self.honestGroup.addButton(self.radioButton_29)
        self.gridLayout_5.addWidget(self.radioButton_29, 24, 2, 1, 1)
        self.radioButton_36 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_36.setObjectName("radioButton_36")
        self.humbleGroup.addButton(self.radioButton_36)
        self.gridLayout_5.addWidget(self.radioButton_36, 26, 0, 1, 1)
        self.radioButton_39 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_39.setObjectName("radioButton_39")
        self.braveGroup.addButton(self.radioButton_39)
        self.gridLayout_5.addWidget(self.radioButton_39, 27, 0, 1, 1)
        self.radioButton_32 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_32.setObjectName("radioButton_32")
        self.patientGroup.addButton(self.radioButton_32)
        self.gridLayout_5.addWidget(self.radioButton_32, 25, 2, 1, 1)
        self.radioButton_28 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_28.setObjectName("radioButton_28")
        self.honestGroup.addButton(self.radioButton_28)
        self.gridLayout_5.addWidget(self.radioButton_28, 24, 1, 1, 1)
        self.radioButton_30 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_30.setObjectName("radioButton_30")
        self.honestGroup.addButton(self.radioButton_30)
        self.gridLayout_5.addWidget(self.radioButton_30, 24, 0, 1, 1)
        self.radioButton_34 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_34.setObjectName("radioButton_34")
        self.humbleGroup.addButton(self.radioButton_34)
        self.gridLayout_5.addWidget(self.radioButton_34, 26, 1, 1, 1)
        self.radioButton_38 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_38.setObjectName("radioButton_38")
        self.braveGroup.addButton(self.radioButton_38)
        self.gridLayout_5.addWidget(self.radioButton_38, 27, 2, 1, 1)
        self.radioButton_42 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_42.setObjectName("radioButton_42")
        self.moneyGroup.addButton(self.radioButton_42)
        self.gridLayout_5.addWidget(self.radioButton_42, 28, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_5.setObjectName("radioButton_5")
        self.traitPlusGroup = QtWidgets.QButtonGroup(MainWindow)
        self.traitPlusGroup.setObjectName("traitPlusGroup")
        self.traitPlusGroup.addButton(self.radioButton_5)
        self.gridLayout_5.addWidget(self.radioButton_5, 7, 1, 1, 2)
        self.radioButton_44 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_44.setObjectName("radioButton_44")
        self.traitPlusGroup.addButton(self.radioButton_44)
        self.gridLayout_5.addWidget(self.radioButton_44, 8, 1, 1, 2)
        self.grtWkLabel = QtWidgets.QLabel(self.wave2Page1)
        self.grtWkLabel.setObjectName("grtWkLabel")
        self.gridLayout_5.addWidget(self.grtWkLabel, 10, 0, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.traitMinusGroup = QtWidgets.QButtonGroup(MainWindow)
        self.traitMinusGroup.setObjectName("traitMinusGroup")
        self.traitMinusGroup.addButton(self.radioButton_6)
        self.gridLayout_5.addWidget(self.radioButton_6, 10, 1, 1, 2)
        self.radioButton = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.traitPlusGroup.addButton(self.radioButton)
        self.gridLayout_5.addWidget(self.radioButton, 2, 1, 1, 2)
        self.grtStrLabel = QtWidgets.QLabel(self.wave2Page1)
        self.grtStrLabel.setObjectName("grtStrLabel")
        self.gridLayout_5.addWidget(self.grtStrLabel, 2, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_2.setObjectName("radioButton_2")
        self.traitPlusGroup.addButton(self.radioButton_2)
        self.gridLayout_5.addWidget(self.radioButton_2, 3, 1, 1, 2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_3.setObjectName("radioButton_3")
        self.traitPlusGroup.addButton(self.radioButton_3)
        self.gridLayout_5.addWidget(self.radioButton_3, 4, 1, 1, 2)
        self.radioButton_4 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_4.setObjectName("radioButton_4")
        self.traitPlusGroup.addButton(self.radioButton_4)
        self.gridLayout_5.addWidget(self.radioButton_4, 5, 1, 1, 2)
        self.radioButton_11 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_11.setObjectName("radioButton_11")
        self.traitPlusGroup.addButton(self.radioButton_11)
        self.gridLayout_5.addWidget(self.radioButton_11, 6, 1, 1, 2)
        self.radioButton_8 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_8.setObjectName("radioButton_8")
        self.traitMinusGroup.addButton(self.radioButton_8)
        self.gridLayout_5.addWidget(self.radioButton_8, 12, 1, 1, 2)
        self.traitsLabel = QtWidgets.QLabel(self.wave2Page1)
        self.traitsLabel.setObjectName("traitsLabel")
        self.gridLayout_5.addWidget(self.traitsLabel, 18, 0, 1, 3)
        self.radioButton_9 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_9.setObjectName("radioButton_9")
        self.traitMinusGroup.addButton(self.radioButton_9)
        self.gridLayout_5.addWidget(self.radioButton_9, 14, 1, 1, 2)
        self.radioButton_12 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_12.setObjectName("radioButton_12")
        self.traitMinusGroup.addButton(self.radioButton_12)
        self.gridLayout_5.addWidget(self.radioButton_12, 15, 1, 1, 2)
        self.radioButton_43 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_43.setObjectName("radioButton_43")
        self.traitMinusGroup.addButton(self.radioButton_43)
        self.gridLayout_5.addWidget(self.radioButton_43, 16, 1, 1, 2)
        self.radioButton_13 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_13.setObjectName("radioButton_13")
        self.senseGroup.addButton(self.radioButton_13)
        self.gridLayout_5.addWidget(self.radioButton_13, 19, 0, 1, 1)
        self.radioButton_14 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_14.setObjectName("radioButton_14")
        self.senseGroup.addButton(self.radioButton_14)
        self.gridLayout_5.addWidget(self.radioButton_14, 19, 1, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_10.setObjectName("radioButton_10")
        self.traitMinusGroup.addButton(self.radioButton_10)
        self.gridLayout_5.addWidget(self.radioButton_10, 13, 1, 1, 2)
        self.radioButton_7 = QtWidgets.QRadioButton(self.wave2Page1)
        self.radioButton_7.setObjectName("radioButton_7")
        self.traitMinusGroup.addButton(self.radioButton_7)
        self.gridLayout_5.addWidget(self.radioButton_7, 11, 1, 1, 2)
        self.line_8 = QtWidgets.QFrame(self.wave2Page1)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_5.addWidget(self.line_8, 9, 0, 1, 3)
        self.wave2Label = QtWidgets.QLabel(self.wave2Page1)
        self.wave2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.wave2Label.setObjectName("wave2Label")
        self.gridLayout_5.addWidget(self.wave2Label, 0, 0, 1, 3)
        self.wave2GenBtn = QtWidgets.QPushButton(self.wave2Page1)
        self.wave2GenBtn.setObjectName("wave2GenBtn")
        self.gridLayout_5.addWidget(self.wave2GenBtn, 29, 0, 1, 3)
        self.wave2Label.raise_()
        self.grtStrLabel.raise_()
        self.grtWkLabel.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.radioButton_5.raise_()
        self.radioButton_6.raise_()
        self.radioButton_7.raise_()
        self.radioButton_8.raise_()
        self.radioButton_9.raise_()
        self.radioButton_10.raise_()
        self.radioButton_11.raise_()
        self.radioButton_12.raise_()
        self.traitsLabel.raise_()
        self.radioButton_13.raise_()
        self.radioButton_14.raise_()
        self.radioButton_15.raise_()
        self.radioButton_16.raise_()
        self.radioButton_17.raise_()
        self.radioButton_18.raise_()
        self.radioButton_19.raise_()
        self.radioButton_21.raise_()
        self.radioButton_22.raise_()
        self.radioButton_23.raise_()
        self.radioButton_24.raise_()
        self.radioButton_25.raise_()
        self.radioButton_26.raise_()
        self.radioButton_27.raise_()
        self.radioButton_28.raise_()
        self.radioButton_29.raise_()
        self.radioButton_30.raise_()
        self.radioButton_31.raise_()
        self.radioButton_32.raise_()
        self.radioButton_33.raise_()
        self.radioButton_34.raise_()
        self.radioButton_35.raise_()
        self.radioButton_36.raise_()
        self.radioButton_37.raise_()
        self.radioButton_38.raise_()
        self.radioButton_39.raise_()
        self.radioButton_40.raise_()
        self.radioButton_41.raise_()
        self.radioButton_42.raise_()
        self.radioButton_43.raise_()
        self.radioButton_44.raise_()
        self.radioButton_20.raise_()
        self.wave2GenBtn.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_8.raise_()
        self.stackedWidget.addWidget(self.wave2Page1)
        self.wave2Results = QtWidgets.QWidget()
        self.wave2Results.setObjectName("wave2Results")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.wave2Results)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.wave2Results)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 2, 0, 1, 2)
        self.listWidget = QtWidgets.QListWidget(self.wave2Results)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_6.addWidget(self.listWidget, 3, 0, 1, 2)
        self.addTraitBtn = QtWidgets.QPushButton(self.wave2Results)
        self.addTraitBtn.setObjectName("addTraitBtn")
        self.gridLayout_6.addWidget(self.addTraitBtn, 4, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.wave2Results)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_6.addWidget(self.line_9, 1, 0, 1, 2)
        self.delTraitBtn = QtWidgets.QPushButton(self.wave2Results)
        self.delTraitBtn.setObjectName("delTraitBtn")
        self.gridLayout_6.addWidget(self.delTraitBtn, 4, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 5, 0, 1, 2)
        self.wave2EndBtn = QtWidgets.QPushButton(self.wave2Results)
        self.wave2EndBtn.setObjectName("wave2EndBtn")
        self.gridLayout_6.addWidget(self.wave2EndBtn, 6, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.wave2Results)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.wave2Results)
        self.wave3Page1 = QtWidgets.QWidget()
        self.wave3Page1.setObjectName("wave3Page1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.wave3Page1)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.wave3Genbtn = QtWidgets.QPushButton(self.wave3Page1)
        self.wave3Genbtn.setObjectName("wave3Genbtn")
        self.gridLayout_7.addWidget(self.wave3Genbtn, 19, 0, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem9, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.wave3Page1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 5, 0, 1, 1)
        self.childBox = QtWidgets.QComboBox(self.wave3Page1)
        self.childBox.setObjectName("childBox")
        self.childBox.addItem("")
        self.childBox.addItem("")
        self.childBox.addItem("")
        self.childBox.addItem("")
        self.childBox.addItem("")
        self.childBox.addItem("")
        self.childBox.addItem("")
        self.gridLayout_7.addWidget(self.childBox, 5, 1, 1, 1)
        self.familyBox = QtWidgets.QComboBox(self.wave3Page1)
        self.familyBox.setObjectName("familyBox")
        self.familyBox.addItem("")
        self.familyBox.addItem("")
        self.familyBox.addItem("")
        self.familyBox.addItem("")
        self.familyBox.addItem("")
        self.gridLayout_7.addWidget(self.familyBox, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.wave3Page1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 7, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem10, 6, 0, 1, 1)
        self.envBox = QtWidgets.QComboBox(self.wave3Page1)
        self.envBox.setObjectName("envBox")
        self.envBox.addItem("")
        self.envBox.addItem("")
        self.envBox.addItem("")
        self.envBox.addItem("")
        self.envBox.addItem("")
        self.envBox.addItem("")
        self.envBox.addItem("")
        self.envBox.addItem("")
        self.gridLayout_7.addWidget(self.envBox, 7, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem11, 1, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.wave3Page1)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_7.addWidget(self.line_10, 2, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.wave3Page1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.wave3Page1)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 9, 0, 1, 1)
        self.socialBox = QtWidgets.QComboBox(self.wave3Page1)
        self.socialBox.setObjectName("socialBox")
        self.socialBox.addItem("")
        self.socialBox.addItem("")
        self.socialBox.addItem("")
        self.socialBox.addItem("")
        self.socialBox.addItem("")
        self.socialBox.addItem("")
        self.gridLayout_7.addWidget(self.socialBox, 9, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.wave3Page1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 11, 0, 1, 1)
        self.goalBox = QtWidgets.QComboBox(self.wave3Page1)
        self.goalBox.setObjectName("goalBox")
        self.goalBox.addItem("")
        self.goalBox.addItem("")
        self.goalBox.addItem("")
        self.goalBox.addItem("")
        self.goalBox.addItem("")
        self.goalBox.addItem("")
        self.goalBox.addItem("")
        self.goalBox.addItem("")
        self.goalBox.addItem("")
        self.goalBox.addItem("")
        self.goalBox.addItem("")
        self.gridLayout_7.addWidget(self.goalBox, 15, 1, 1, 1)
        self.rolemodelBox = QtWidgets.QComboBox(self.wave3Page1)
        self.rolemodelBox.setObjectName("rolemodelBox")
        self.rolemodelBox.addItem("")
        self.rolemodelBox.addItem("")
        self.rolemodelBox.addItem("")
        self.rolemodelBox.addItem("")
        self.rolemodelBox.addItem("")
        self.rolemodelBox.addItem("")
        self.rolemodelBox.addItem("")
        self.rolemodelBox.addItem("")
        self.rolemodelBox.addItem("")
        self.gridLayout_7.addWidget(self.rolemodelBox, 11, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.wave3Page1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 13, 0, 1, 1)
        self.memBox = QtWidgets.QComboBox(self.wave3Page1)
        self.memBox.setObjectName("memBox")
        self.memBox.addItem("")
        self.memBox.addItem("")
        self.memBox.addItem("")
        self.memBox.addItem("")
        self.memBox.addItem("")
        self.memBox.addItem("")
        self.memBox.addItem("")
        self.memBox.addItem("")
        self.gridLayout_7.addWidget(self.memBox, 13, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.wave3Page1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 15, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem12, 16, 0, 1, 1)
        self.ageBox = QtWidgets.QComboBox(self.wave3Page1)
        self.ageBox.setObjectName("ageBox")
        self.ageBox.addItem("")
        self.ageBox.addItem("")
        self.ageBox.addItem("")
        self.ageBox.addItem("")
        self.ageBox.addItem("")
        self.ageBox.addItem("")
        self.ageBox.addItem("")
        self.gridLayout_7.addWidget(self.ageBox, 17, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem13, 12, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem14, 8, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem15, 10, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.wave3Page1)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 17, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem16, 14, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem17, 18, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.wave3Page1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.wave3Page1)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 0, 2, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.page)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_8.addWidget(self.line_11, 1, 0, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 2, 0, 1, 3)
        self.bList1 = QtWidgets.QListWidget(self.page)
        self.bList1.setObjectName("bList1")
        self.gridLayout_8.addWidget(self.bList1, 3, 2, 1, 1)
        self.radioButton_46 = QtWidgets.QRadioButton(self.page)
        self.radioButton_46.setText("")
        self.radioButton_46.setObjectName("radioButton_46")
        self.backgroundGroup = QtWidgets.QButtonGroup(MainWindow)
        self.backgroundGroup.setObjectName("backgroundGroup")
        self.backgroundGroup.addButton(self.radioButton_46)
        self.gridLayout_8.addWidget(self.radioButton_46, 4, 0, 1, 2)
        self.bList2 = QtWidgets.QListWidget(self.page)
        self.bList2.setObjectName("bList2")
        self.gridLayout_8.addWidget(self.bList2, 4, 2, 1, 1)
        self.radioButton_47 = QtWidgets.QRadioButton(self.page)
        self.radioButton_47.setText("")
        self.radioButton_47.setObjectName("radioButton_47")
        self.backgroundGroup.addButton(self.radioButton_47)
        self.gridLayout_8.addWidget(self.radioButton_47, 5, 0, 1, 1)
        self.radioButton_45 = QtWidgets.QRadioButton(self.page)
        self.radioButton_45.setText("")
        self.radioButton_45.setChecked(True)
        self.radioButton_45.setObjectName("radioButton_45")
        self.backgroundGroup.addButton(self.radioButton_45)
        self.gridLayout_8.addWidget(self.radioButton_45, 3, 0, 1, 1)
        self.bList3 = QtWidgets.QListWidget(self.page)
        self.bList3.setObjectName("bList3")
        self.gridLayout_8.addWidget(self.bList3, 5, 2, 1, 1)
        self.finishButton = QtWidgets.QPushButton(self.page)
        self.finishButton.setObjectName("finishButton")
        self.gridLayout_8.addWidget(self.finishButton, 6, 0, 1, 3)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.newCharBtn = QtWidgets.QPushButton(self.page_2)
        self.newCharBtn.setObjectName("newCharBtn")
        self.gridLayout_14.addWidget(self.newCharBtn, 7, 0, 1, 2)
        self.statTable = QtWidgets.QTableWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statTable.sizePolicy().hasHeightForWidth())
        self.statTable.setSizePolicy(sizePolicy)
        self.statTable.setMaximumSize(QtCore.QSize(202, 205))
        self.statTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.statTable.setAlternatingRowColors(True)
        self.statTable.setRowCount(6)
        self.statTable.setColumnCount(2)
        self.statTable.setObjectName("statTable")
        item = QtWidgets.QTableWidgetItem()
        self.statTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statTable.setItem(5, 0, item)
        self.statTable.verticalHeader().setVisible(False)
        self.gridLayout_14.addWidget(self.statTable, 5, 0, 1, 3)
        self.bckgrndText = QtWidgets.QPlainTextEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bckgrndText.sizePolicy().hasHeightForWidth())
        self.bckgrndText.setSizePolicy(sizePolicy)
        self.bckgrndText.setMaximumSize(QtCore.QSize(425, 16777215))
        self.bckgrndText.setObjectName("bckgrndText")
        self.gridLayout_14.addWidget(self.bckgrndText, 6, 0, 1, 6)
        self.skillTable = QtWidgets.QTableWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skillTable.sizePolicy().hasHeightForWidth())
        self.skillTable.setSizePolicy(sizePolicy)
        self.skillTable.setMaximumSize(QtCore.QSize(219, 205))
        self.skillTable.setAlternatingRowColors(True)
        self.skillTable.setObjectName("skillTable")
        self.skillTable.setColumnCount(2)
        self.skillTable.setRowCount(26)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(19, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(21, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(22, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(23, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(24, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skillTable.setItem(25, 0, item)
        self.skillTable.verticalHeader().setVisible(False)
        self.gridLayout_14.addWidget(self.skillTable, 5, 3, 1, 3)
        self.exportBtn = QtWidgets.QPushButton(self.page_2)
        self.exportBtn.setObjectName("exportBtn")
        self.gridLayout_14.addWidget(self.exportBtn, 7, 4, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_14.addWidget(self.label_14, 0, 2, 1, 2)
        self.label_44 = QtWidgets.QLabel(self.page_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_14.addWidget(self.label_44, 3, 0, 1, 1)
        self.raceLbl = QtWidgets.QLabel(self.page_2)
        self.raceLbl.setObjectName("raceLbl")
        self.gridLayout_14.addWidget(self.raceLbl, 3, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.page_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_14.addWidget(self.label_43, 2, 0, 1, 1)
        self.nameLbl = QtWidgets.QLabel(self.page_2)
        self.nameLbl.setObjectName("nameLbl")
        self.gridLayout_14.addWidget(self.nameLbl, 2, 1, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.page_2)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout_14.addWidget(self.line_21, 1, 0, 1, 6)
        self.label_45 = QtWidgets.QLabel(self.page_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_14.addWidget(self.label_45, 2, 3, 1, 1)
        self.classLbl = QtWidgets.QLabel(self.page_2)
        self.classLbl.setObjectName("classLbl")
        self.gridLayout_14.addWidget(self.classLbl, 2, 4, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.page_2)
        self.label_48.setObjectName("label_48")
        self.gridLayout_14.addWidget(self.label_48, 3, 3, 1, 1)
        self.ageLbl = QtWidgets.QLabel(self.page_2)
        self.ageLbl.setObjectName("ageLbl")
        self.gridLayout_14.addWidget(self.ageLbl, 3, 4, 1, 1)
        self.label_14.raise_()
        self.bckgrndText.raise_()
        self.label_43.raise_()
        self.label_44.raise_()
        self.skillTable.raise_()
        self.statTable.raise_()
        self.newCharBtn.raise_()
        self.exportBtn.raise_()
        self.nameLbl.raise_()
        self.raceLbl.raise_()
        self.line_21.raise_()
        self.label_45.raise_()
        self.classLbl.raise_()
        self.label_48.raise_()
        self.ageLbl.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 2, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 0, 3, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem18, 0, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 0, 4, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.nameLabel.setBuddy(self.nameEdit)
        self.raceLabel.setBuddy(self.raceBox)
        self.classLabel.setBuddy(self.classBox)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Session Zero"))
        self.titleLabel.setText(_translate("MainWindow", "Session Zero"))
        self.buildBtn.setText(_translate("MainWindow", "Build a Character"))
        self.loadBtn.setText(_translate("MainWindow", "Load a Character"))
        self.wave1Label.setText(_translate("MainWindow", "Basic Character Information"))
        self.nameLabel.setText(_translate("MainWindow", "Name:"))
        self.raceLabel.setText(_translate("MainWindow", "Race:"))
        self.raceBox.setItemText(0, _translate("MainWindow", "Dwarf"))
        self.raceBox.setItemText(1, _translate("MainWindow", "Halfling"))
        self.raceBox.setItemText(2, _translate("MainWindow", "Elf"))
        self.raceBox.setItemText(3, _translate("MainWindow", "Human"))
        self.raceBox.setItemText(4, _translate("MainWindow", "Gnome"))
        self.raceBox.setItemText(5, _translate("MainWindow", "Half-orc"))
        self.raceBox.setItemText(6, _translate("MainWindow", "Half-elf"))
        self.classLabel.setText(_translate("MainWindow", "Class: "))
        self.classBox.setItemText(0, _translate("MainWindow", "Adept"))
        self.classBox.setItemText(1, _translate("MainWindow", "Aristocrat"))
        self.classBox.setItemText(2, _translate("MainWindow", "Barbarian"))
        self.classBox.setItemText(3, _translate("MainWindow", "Bard"))
        self.classBox.setItemText(4, _translate("MainWindow", "Cleric"))
        self.classBox.setItemText(5, _translate("MainWindow", "Commoner"))
        self.classBox.setItemText(6, _translate("MainWindow", "Druid"))
        self.classBox.setItemText(7, _translate("MainWindow", "Expert"))
        self.classBox.setItemText(8, _translate("MainWindow", "Fighter"))
        self.classBox.setItemText(9, _translate("MainWindow", "Monk"))
        self.classBox.setItemText(10, _translate("MainWindow", "Paladin"))
        self.classBox.setItemText(11, _translate("MainWindow", "Ranger"))
        self.classBox.setItemText(12, _translate("MainWindow", "Rogue"))
        self.classBox.setItemText(13, _translate("MainWindow", "Sorcerer"))
        self.classBox.setItemText(14, _translate("MainWindow", "Warrior"))
        self.classBox.setItemText(15, _translate("MainWindow", "Wizard"))
        self.statsPlusLabel.setText(_translate("MainWindow", "Strengths:"))
        self.checkBox_2.setText(_translate("MainWindow", "Strong"))
        self.checkBox_3.setText(_translate("MainWindow", "Quick"))
        self.checkBox_4.setText(_translate("MainWindow", "Hardy"))
        self.checkBox_5.setText(_translate("MainWindow", "Intelligent"))
        self.checkBox.setText(_translate("MainWindow", "Wise"))
        self.checkBox_6.setText(_translate("MainWindow", "Charismatic"))
        self.statsMinusLabel.setText(_translate("MainWindow", "Weaknesses:    "))
        self.checkBox_8.setText(_translate("MainWindow", "Weak"))
        self.checkBox_11.setText(_translate("MainWindow", "Slow"))
        self.checkBox_10.setText(_translate("MainWindow", "Frail"))
        self.checkBox_12.setText(_translate("MainWindow", "Stupid"))
        self.checkBox_7.setText(_translate("MainWindow", "Imprudent"))
        self.checkBox_9.setText(_translate("MainWindow", "Impersonable"))
        self.wave1GenBtn.setText(_translate("MainWindow", "Generate Statblock"))
        item = self.statblock2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stat"))
        item = self.statblock2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.statblock2.isSortingEnabled()
        self.statblock2.setSortingEnabled(False)
        item = self.statblock2.item(0, 0)
        item.setText(_translate("MainWindow", "Strength"))
        item = self.statblock2.item(1, 0)
        item.setText(_translate("MainWindow", "Dexterity"))
        item = self.statblock2.item(2, 0)
        item.setText(_translate("MainWindow", "Constitution"))
        item = self.statblock2.item(3, 0)
        item.setText(_translate("MainWindow", "Intelligence"))
        item = self.statblock2.item(4, 0)
        item.setText(_translate("MainWindow", "Wisdom"))
        item = self.statblock2.item(5, 0)
        item.setText(_translate("MainWindow", "Charisma"))
        self.statblock2.setSortingEnabled(__sortingEnabled)
        self.selectBtn3.setText(_translate("MainWindow", "Select"))
        item = self.statblock3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stat"))
        item = self.statblock3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.statblock3.isSortingEnabled()
        self.statblock3.setSortingEnabled(False)
        item = self.statblock3.item(0, 0)
        item.setText(_translate("MainWindow", "Strength"))
        item = self.statblock3.item(1, 0)
        item.setText(_translate("MainWindow", "Dexterity"))
        item = self.statblock3.item(2, 0)
        item.setText(_translate("MainWindow", "Constitution"))
        item = self.statblock3.item(3, 0)
        item.setText(_translate("MainWindow", "Intelligence"))
        item = self.statblock3.item(4, 0)
        item.setText(_translate("MainWindow", "Wisdom"))
        item = self.statblock3.item(5, 0)
        item.setText(_translate("MainWindow", "Charisma"))
        self.statblock3.setSortingEnabled(__sortingEnabled)
        self.genLabel.setText(_translate("MainWindow", "Basic Character Information"))
        self.statblockLabel.setText(_translate("MainWindow", "Select the statblock that fits your character best"))
        self.selectBtn1.setText(_translate("MainWindow", "Select"))
        item = self.statblock1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stat"))
        item = self.statblock1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.statblock1.isSortingEnabled()
        self.statblock1.setSortingEnabled(False)
        item = self.statblock1.item(0, 0)
        item.setText(_translate("MainWindow", "Strength"))
        item = self.statblock1.item(1, 0)
        item.setText(_translate("MainWindow", "Dexterity"))
        item = self.statblock1.item(2, 0)
        item.setText(_translate("MainWindow", "Constitution"))
        item = self.statblock1.item(3, 0)
        item.setText(_translate("MainWindow", "Intelligence"))
        item = self.statblock1.item(4, 0)
        item.setText(_translate("MainWindow", "Wisdom"))
        item = self.statblock1.item(5, 0)
        item.setText(_translate("MainWindow", "Charisma"))
        self.statblock1.setSortingEnabled(__sortingEnabled)
        self.selectBtn2.setText(_translate("MainWindow", "Select"))
        self.wave1EndBtn.setText(_translate("MainWindow", "Continue"))
        self.radioButton_27.setText(_translate("MainWindow", "Sycophantic"))
        self.radioButton_25.setText(_translate("MainWindow", "Friendly"))
        self.radioButton_15.setText(_translate("MainWindow", "Insensible"))
        self.radioButton_16.setText(_translate("MainWindow", "Caring"))
        self.radioButton_19.setText(_translate("MainWindow", "Modest"))
        self.radioButton_21.setText(_translate("MainWindow", "Shy"))
        self.radioButton_17.setText(_translate("MainWindow", "Aloof"))
        self.radioButton_20.setText(_translate("MainWindow", "Shameless"))
        self.radioButton_24.setText(_translate("MainWindow", "Foolish"))
        self.radioButton_18.setText(_translate("MainWindow", "Empathetic"))
        self.radioButton_22.setText(_translate("MainWindow", "Witty"))
        self.radioButton_23.setText(_translate("MainWindow", "Boorish"))
        self.radioButton_35.setText(_translate("MainWindow", "Unambitious"))
        self.radioButton_26.setText(_translate("MainWindow", "Independent"))
        self.radioButton_37.setText(_translate("MainWindow", "Brave"))
        self.radioButton_41.setText(_translate("MainWindow", "Drab"))
        self.radioButton_33.setText(_translate("MainWindow", "Wrathful"))
        self.radioButton_40.setText(_translate("MainWindow", "Reserved"))
        self.radioButton_31.setText(_translate("MainWindow", "Patient"))
        self.radioButton_29.setText(_translate("MainWindow", "Understated"))
        self.radioButton_36.setText(_translate("MainWindow", "Self-absorbed"))
        self.radioButton_39.setText(_translate("MainWindow", "Rash"))
        self.radioButton_32.setText(_translate("MainWindow", "Numb"))
        self.radioButton_28.setText(_translate("MainWindow", "Honest"))
        self.radioButton_30.setText(_translate("MainWindow", "Boastful"))
        self.radioButton_34.setText(_translate("MainWindow", "Humble"))
        self.radioButton_38.setText(_translate("MainWindow", "Cowardly"))
        self.radioButton_42.setText(_translate("MainWindow", "Ostentatious"))
        self.radioButton_5.setText(_translate("MainWindow", "Curiosity"))
        self.radioButton_44.setText(_translate("MainWindow", "Creativity"))
        self.grtWkLabel.setText(_translate("MainWindow", "Greatest Weakness:"))
        self.radioButton_6.setText(_translate("MainWindow", "Anger"))
        self.radioButton.setText(_translate("MainWindow", "Loyalty"))
        self.grtStrLabel.setText(_translate("MainWindow", "Greatest Strength:"))
        self.radioButton_2.setText(_translate("MainWindow", "Compassion"))
        self.radioButton_3.setText(_translate("MainWindow", "Discipline"))
        self.radioButton_4.setText(_translate("MainWindow", "Optimism"))
        self.radioButton_11.setText(_translate("MainWindow", "Tolerance"))
        self.radioButton_8.setText(_translate("MainWindow", "Insecurity"))
        self.traitsLabel.setText(_translate("MainWindow", "What traits does your character possess?"))
        self.radioButton_9.setText(_translate("MainWindow", "Laziness"))
        self.radioButton_12.setText(_translate("MainWindow", "Pride"))
        self.radioButton_43.setText(_translate("MainWindow", "Envy"))
        self.radioButton_13.setText(_translate("MainWindow", "Indulgent"))
        self.radioButton_14.setText(_translate("MainWindow", "Restrained"))
        self.radioButton_10.setText(_translate("MainWindow", "Lust"))
        self.radioButton_7.setText(_translate("MainWindow", "Greed"))
        self.wave2Label.setText(_translate("MainWindow", "Personality Traits"))
        self.wave2GenBtn.setText(_translate("MainWindow", "Generate Additional Traits"))
        self.label_2.setText(_translate("MainWindow", "Add or remove traits to better describe your character"))
        self.addTraitBtn.setText(_translate("MainWindow", "Add Trait"))
        self.delTraitBtn.setText(_translate("MainWindow", "Remove Trait"))
        self.wave2EndBtn.setText(_translate("MainWindow", "Continue"))
        self.label.setText(_translate("MainWindow", "Personality Traits"))
        self.wave3Genbtn.setText(_translate("MainWindow", "Generate Background"))
        self.label_5.setText(_translate("MainWindow", "How was their childhood?"))
        self.childBox.setItemText(0, _translate("MainWindow", "lonely"))
        self.childBox.setItemText(1, _translate("MainWindow", "abusive"))
        self.childBox.setItemText(2, _translate("MainWindow", "loving"))
        self.childBox.setItemText(3, _translate("MainWindow", "happy"))
        self.childBox.setItemText(4, _translate("MainWindow", "tragic"))
        self.childBox.setItemText(5, _translate("MainWindow", "peaceful"))
        self.childBox.setItemText(6, _translate("MainWindow", "exhausting"))
        self.familyBox.setItemText(0, _translate("MainWindow", "large family"))
        self.familyBox.setItemText(1, _translate("MainWindow", "only child"))
        self.familyBox.setItemText(2, _translate("MainWindow", "orphan"))
        self.familyBox.setItemText(3, _translate("MainWindow", "one parent"))
        self.familyBox.setItemText(4, _translate("MainWindow", "none"))
        self.label_6.setText(_translate("MainWindow", "What was their environment growing up?"))
        self.envBox.setItemText(0, _translate("MainWindow", "large city"))
        self.envBox.setItemText(1, _translate("MainWindow", "noble palace"))
        self.envBox.setItemText(2, _translate("MainWindow", "religious community"))
        self.envBox.setItemText(3, _translate("MainWindow", "slums"))
        self.envBox.setItemText(4, _translate("MainWindow", "traveling"))
        self.envBox.setItemText(5, _translate("MainWindow", "isolated area"))
        self.envBox.setItemText(6, _translate("MainWindow", "small village"))
        self.envBox.setItemText(7, _translate("MainWindow", "place of learning"))
        self.label_4.setText(_translate("MainWindow", "What is your character\'s family situation?"))
        self.label_10.setText(_translate("MainWindow", "What was their social class?"))
        self.socialBox.setItemText(0, _translate("MainWindow", "lower class"))
        self.socialBox.setItemText(1, _translate("MainWindow", "merchant class"))
        self.socialBox.setItemText(2, _translate("MainWindow", "aristocrat"))
        self.socialBox.setItemText(3, _translate("MainWindow", "royalty"))
        self.socialBox.setItemText(4, _translate("MainWindow", "upper class"))
        self.socialBox.setItemText(5, _translate("MainWindow", "none"))
        self.label_7.setText(_translate("MainWindow", "Who was their role model?"))
        self.goalBox.setItemText(0, _translate("MainWindow", "true love"))
        self.goalBox.setItemText(1, _translate("MainWindow", "revenge"))
        self.goalBox.setItemText(2, _translate("MainWindow", "save a life"))
        self.goalBox.setItemText(3, _translate("MainWindow", "wealth"))
        self.goalBox.setItemText(4, _translate("MainWindow", "power"))
        self.goalBox.setItemText(5, _translate("MainWindow", "freedom"))
        self.goalBox.setItemText(6, _translate("MainWindow", "see the world"))
        self.goalBox.setItemText(7, _translate("MainWindow", "be a hero"))
        self.goalBox.setItemText(8, _translate("MainWindow", "survive"))
        self.goalBox.setItemText(9, _translate("MainWindow", "obtain knowledge"))
        self.goalBox.setItemText(10, _translate("MainWindow", "provide for family"))
        self.rolemodelBox.setItemText(0, _translate("MainWindow", "parent"))
        self.rolemodelBox.setItemText(1, _translate("MainWindow", "sibling"))
        self.rolemodelBox.setItemText(2, _translate("MainWindow", "folk hero"))
        self.rolemodelBox.setItemText(3, _translate("MainWindow", "local lord"))
        self.rolemodelBox.setItemText(4, _translate("MainWindow", "ruler"))
        self.rolemodelBox.setItemText(5, _translate("MainWindow", "teacher"))
        self.rolemodelBox.setItemText(6, _translate("MainWindow", "older youth"))
        self.rolemodelBox.setItemText(7, _translate("MainWindow", "adventurer"))
        self.rolemodelBox.setItemText(8, _translate("MainWindow", "other family member"))
        self.label_9.setText(_translate("MainWindow", "What is a formative memory of theirs?"))
        self.memBox.setItemText(0, _translate("MainWindow", "death in the family"))
        self.memBox.setItemText(1, _translate("MainWindow", "being punished"))
        self.memBox.setItemText(2, _translate("MainWindow", "home invaded"))
        self.memBox.setItemText(3, _translate("MainWindow", "first kiss"))
        self.memBox.setItemText(4, _translate("MainWindow", "friend\'s death"))
        self.memBox.setItemText(5, _translate("MainWindow", "assault"))
        self.memBox.setItemText(6, _translate("MainWindow", "caught stealing"))
        self.memBox.setItemText(7, _translate("MainWindow", "ran away from home"))
        self.label_8.setText(_translate("MainWindow", "What is their current goal?"))
        self.ageBox.setItemText(0, _translate("MainWindow", "child"))
        self.ageBox.setItemText(1, _translate("MainWindow", "adolescent"))
        self.ageBox.setItemText(2, _translate("MainWindow", "adult"))
        self.ageBox.setItemText(3, _translate("MainWindow", "middle-aged"))
        self.ageBox.setItemText(4, _translate("MainWindow", "old"))
        self.ageBox.setItemText(5, _translate("MainWindow", "venerable"))
        self.ageBox.setItemText(6, _translate("MainWindow", "immortal"))
        self.label_11.setText(_translate("MainWindow", "How old are they?"))
        self.label_3.setText(_translate("MainWindow", "Character Background and Motivation"))
        self.label_12.setText(_translate("MainWindow", "Character Background and Motivation"))
        self.label_13.setText(_translate("MainWindow", "Select the additional traits that come from your character\'s background."))
        self.finishButton.setText(_translate("MainWindow", "Finish"))
        self.newCharBtn.setText(_translate("MainWindow", "Make New Character"))
        item = self.statTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stat"))
        item = self.statTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.statTable.isSortingEnabled()
        self.statTable.setSortingEnabled(False)
        item = self.statTable.item(0, 0)
        item.setText(_translate("MainWindow", "Strength"))
        item = self.statTable.item(1, 0)
        item.setText(_translate("MainWindow", "Dexterity"))
        item = self.statTable.item(2, 0)
        item.setText(_translate("MainWindow", "Constitution"))
        item = self.statTable.item(3, 0)
        item.setText(_translate("MainWindow", "Intelligence"))
        item = self.statTable.item(4, 0)
        item.setText(_translate("MainWindow", "Wisdom"))
        item = self.statTable.item(5, 0)
        item.setText(_translate("MainWindow", "Charisma"))
        self.statTable.setSortingEnabled(__sortingEnabled)
        self.bckgrndText.setDocumentTitle(_translate("MainWindow", "Background and Description"))
        item = self.skillTable.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.skillTable.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.skillTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Skill"))
        item = self.skillTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Modifier"))
        __sortingEnabled = self.skillTable.isSortingEnabled()
        self.skillTable.setSortingEnabled(False)
        item = self.skillTable.item(0, 0)
        item.setText(_translate("MainWindow", "Acrobatics"))
        item = self.skillTable.item(1, 0)
        item.setText(_translate("MainWindow", "Appraise"))
        item = self.skillTable.item(2, 0)
        item.setText(_translate("MainWindow", "Bluff"))
        item = self.skillTable.item(3, 0)
        item.setText(_translate("MainWindow", "Climb"))
        item = self.skillTable.item(4, 0)
        item.setText(_translate("MainWindow", "Craft"))
        item = self.skillTable.item(5, 0)
        item.setText(_translate("MainWindow", "Diplomacy"))
        item = self.skillTable.item(6, 0)
        item.setText(_translate("MainWindow", "Disable Device"))
        item = self.skillTable.item(7, 0)
        item.setText(_translate("MainWindow", "Disguise"))
        item = self.skillTable.item(8, 0)
        item.setText(_translate("MainWindow", "Escape Artist"))
        item = self.skillTable.item(9, 0)
        item.setText(_translate("MainWindow", "Fly"))
        item = self.skillTable.item(10, 0)
        item.setText(_translate("MainWindow", "Handle Animal"))
        item = self.skillTable.item(11, 0)
        item.setText(_translate("MainWindow", "Heal"))
        item = self.skillTable.item(12, 0)
        item.setText(_translate("MainWindow", "Intimidate"))
        item = self.skillTable.item(13, 0)
        item.setText(_translate("MainWindow", "Knowledge"))
        item = self.skillTable.item(14, 0)
        item.setText(_translate("MainWindow", "Linguistics"))
        item = self.skillTable.item(15, 0)
        item.setText(_translate("MainWindow", "Perception"))
        item = self.skillTable.item(16, 0)
        item.setText(_translate("MainWindow", "Perform"))
        item = self.skillTable.item(17, 0)
        item.setText(_translate("MainWindow", "Profession"))
        item = self.skillTable.item(18, 0)
        item.setText(_translate("MainWindow", "Ride"))
        item = self.skillTable.item(19, 0)
        item.setText(_translate("MainWindow", "Sense Motive"))
        item = self.skillTable.item(20, 0)
        item.setText(_translate("MainWindow", "Sleight of Hand"))
        item = self.skillTable.item(21, 0)
        item.setText(_translate("MainWindow", "Spellcraft"))
        item = self.skillTable.item(22, 0)
        item.setText(_translate("MainWindow", "Stealth"))
        item = self.skillTable.item(23, 0)
        item.setText(_translate("MainWindow", "Survival"))
        item = self.skillTable.item(24, 0)
        item.setText(_translate("MainWindow", "Swim"))
        item = self.skillTable.item(25, 0)
        item.setText(_translate("MainWindow", "Use Magic Device"))
        self.skillTable.setSortingEnabled(__sortingEnabled)
        self.exportBtn.setText(_translate("MainWindow", "Export Character"))
        self.label_14.setText(_translate("MainWindow", "Character Sheet"))
        self.label_44.setText(_translate("MainWindow", "Race:"))
        self.raceLbl.setText(_translate("MainWindow", "TextLabel"))
        self.label_43.setText(_translate("MainWindow", "Name:"))
        self.nameLbl.setText(_translate("MainWindow", "TextLabel"))
        self.label_45.setText(_translate("MainWindow", "Class:"))
        self.classLbl.setText(_translate("MainWindow", "TextLabel"))
        self.label_48.setText(_translate("MainWindow", "Age:"))
        self.ageLbl.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

